/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-10-23 at 04:35:07 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.loanEndPoint.model;

/**
 * Model definition for CallHistory.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the loanEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CallHistory extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long fromId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fromName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fromType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String knowlarity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long time;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long toId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String toName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String toType;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getFromId() {
    return fromId;
  }

  /**
   * @param fromId fromId or {@code null} for none
   */
  public CallHistory setFromId(java.lang.Long fromId) {
    this.fromId = fromId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFromName() {
    return fromName;
  }

  /**
   * @param fromName fromName or {@code null} for none
   */
  public CallHistory setFromName(java.lang.String fromName) {
    this.fromName = fromName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFromType() {
    return fromType;
  }

  /**
   * @param fromType fromType or {@code null} for none
   */
  public CallHistory setFromType(java.lang.String fromType) {
    this.fromType = fromType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public CallHistory setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKnowlarity() {
    return knowlarity;
  }

  /**
   * @param knowlarity knowlarity or {@code null} for none
   */
  public CallHistory setKnowlarity(java.lang.String knowlarity) {
    this.knowlarity = knowlarity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTime() {
    return time;
  }

  /**
   * @param time time or {@code null} for none
   */
  public CallHistory setTime(java.lang.Long time) {
    this.time = time;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getToId() {
    return toId;
  }

  /**
   * @param toId toId or {@code null} for none
   */
  public CallHistory setToId(java.lang.Long toId) {
    this.toId = toId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getToName() {
    return toName;
  }

  /**
   * @param toName toName or {@code null} for none
   */
  public CallHistory setToName(java.lang.String toName) {
    this.toName = toName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getToType() {
    return toType;
  }

  /**
   * @param toType toType or {@code null} for none
   */
  public CallHistory setToType(java.lang.String toType) {
    this.toType = toType;
    return this;
  }

  @Override
  public CallHistory set(String fieldName, Object value) {
    return (CallHistory) super.set(fieldName, value);
  }

  @Override
  public CallHistory clone() {
    return (CallHistory) super.clone();
  }

}
