/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-10-23 at 04:35:07 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.loanEndPoint.model;

/**
 * Model definition for DriveView.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the loanEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DriveView extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double endLat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double endLong;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String kml;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String latLongUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nearbyUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Image projectLogo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double startLat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double startLong;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String thumb;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String videoURL;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getEndLat() {
    return endLat;
  }

  /**
   * @param endLat endLat or {@code null} for none
   */
  public DriveView setEndLat(java.lang.Double endLat) {
    this.endLat = endLat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getEndLong() {
    return endLong;
  }

  /**
   * @param endLong endLong or {@code null} for none
   */
  public DriveView setEndLong(java.lang.Double endLong) {
    this.endLong = endLong;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public DriveView setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKml() {
    return kml;
  }

  /**
   * @param kml kml or {@code null} for none
   */
  public DriveView setKml(java.lang.String kml) {
    this.kml = kml;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLatLongUrl() {
    return latLongUrl;
  }

  /**
   * @param latLongUrl latLongUrl or {@code null} for none
   */
  public DriveView setLatLongUrl(java.lang.String latLongUrl) {
    this.latLongUrl = latLongUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public DriveView setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNearbyUrl() {
    return nearbyUrl;
  }

  /**
   * @param nearbyUrl nearbyUrl or {@code null} for none
   */
  public DriveView setNearbyUrl(java.lang.String nearbyUrl) {
    this.nearbyUrl = nearbyUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Image getProjectLogo() {
    return projectLogo;
  }

  /**
   * @param projectLogo projectLogo or {@code null} for none
   */
  public DriveView setProjectLogo(Image projectLogo) {
    this.projectLogo = projectLogo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getStartLat() {
    return startLat;
  }

  /**
   * @param startLat startLat or {@code null} for none
   */
  public DriveView setStartLat(java.lang.Double startLat) {
    this.startLat = startLat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getStartLong() {
    return startLong;
  }

  /**
   * @param startLong startLong or {@code null} for none
   */
  public DriveView setStartLong(java.lang.Double startLong) {
    this.startLong = startLong;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getThumb() {
    return thumb;
  }

  /**
   * @param thumb thumb or {@code null} for none
   */
  public DriveView setThumb(java.lang.String thumb) {
    this.thumb = thumb;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getVideoURL() {
    return videoURL;
  }

  /**
   * @param videoURL videoURL or {@code null} for none
   */
  public DriveView setVideoURL(java.lang.String videoURL) {
    this.videoURL = videoURL;
    return this;
  }

  @Override
  public DriveView set(String fieldName, Object value) {
    return (DriveView) super.set(fieldName, value);
  }

  @Override
  public DriveView clone() {
    return (DriveView) super.clone();
  }

}
