/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-10-23 at 04:35:07 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.loanEndPoint.model;

/**
 * Model definition for SpotIncentive.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the loanEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SpotIncentive extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long agentId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String agentName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float amount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long bookingId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Document> documentList;

  static {
    // hack to force ProGuard to consider Document used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(Document.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String employeeType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String month;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float paidAmount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long supervisorId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String supervisorName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer year;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getAgentId() {
    return agentId;
  }

  /**
   * @param agentId agentId or {@code null} for none
   */
  public SpotIncentive setAgentId(java.lang.Long agentId) {
    this.agentId = agentId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAgentName() {
    return agentName;
  }

  /**
   * @param agentName agentName or {@code null} for none
   */
  public SpotIncentive setAgentName(java.lang.String agentName) {
    this.agentName = agentName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getAmount() {
    return amount;
  }

  /**
   * @param amount amount or {@code null} for none
   */
  public SpotIncentive setAmount(java.lang.Float amount) {
    this.amount = amount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getBookingId() {
    return bookingId;
  }

  /**
   * @param bookingId bookingId or {@code null} for none
   */
  public SpotIncentive setBookingId(java.lang.Long bookingId) {
    this.bookingId = bookingId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Document> getDocumentList() {
    return documentList;
  }

  /**
   * @param documentList documentList or {@code null} for none
   */
  public SpotIncentive setDocumentList(java.util.List<Document> documentList) {
    this.documentList = documentList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmployeeType() {
    return employeeType;
  }

  /**
   * @param employeeType employeeType or {@code null} for none
   */
  public SpotIncentive setEmployeeType(java.lang.String employeeType) {
    this.employeeType = employeeType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public SpotIncentive setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMonth() {
    return month;
  }

  /**
   * @param month month or {@code null} for none
   */
  public SpotIncentive setMonth(java.lang.String month) {
    this.month = month;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getPaidAmount() {
    return paidAmount;
  }

  /**
   * @param paidAmount paidAmount or {@code null} for none
   */
  public SpotIncentive setPaidAmount(java.lang.Float paidAmount) {
    this.paidAmount = paidAmount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public SpotIncentive setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getSupervisorId() {
    return supervisorId;
  }

  /**
   * @param supervisorId supervisorId or {@code null} for none
   */
  public SpotIncentive setSupervisorId(java.lang.Long supervisorId) {
    this.supervisorId = supervisorId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSupervisorName() {
    return supervisorName;
  }

  /**
   * @param supervisorName supervisorName or {@code null} for none
   */
  public SpotIncentive setSupervisorName(java.lang.String supervisorName) {
    this.supervisorName = supervisorName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getYear() {
    return year;
  }

  /**
   * @param year year or {@code null} for none
   */
  public SpotIncentive setYear(java.lang.Integer year) {
    this.year = year;
    return this;
  }

  @Override
  public SpotIncentive set(String fieldName, Object value) {
    return (SpotIncentive) super.set(fieldName, value);
  }

  @Override
  public SpotIncentive clone() {
    return (SpotIncentive) super.clone();
  }

}
