/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-02-26 17:53:51 UTC)
 * on 2018-03-14 at 11:50:18 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.decorEndPoint.model;

/**
 * Model definition for Decor.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the decorEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Decor extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long createTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<DecorItem> decorItems;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<DecorTag> decorTags;

  static {
    // hack to force ProGuard to consider DecorTag used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(DecorTag.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String metaDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String metaKeyword;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String searchTitle;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String seourl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String source;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sourceUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<TimeLineStats> timeLineStates;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private DecorItem titleSection;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCreateTime() {
    return createTime;
  }

  /**
   * @param createTime createTime or {@code null} for none
   */
  public Decor setCreateTime(java.lang.Long createTime) {
    this.createTime = createTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<DecorItem> getDecorItems() {
    return decorItems;
  }

  /**
   * @param decorItems decorItems or {@code null} for none
   */
  public Decor setDecorItems(java.util.List<DecorItem> decorItems) {
    this.decorItems = decorItems;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<DecorTag> getDecorTags() {
    return decorTags;
  }

  /**
   * @param decorTags decorTags or {@code null} for none
   */
  public Decor setDecorTags(java.util.List<DecorTag> decorTags) {
    this.decorTags = decorTags;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMetaDescription() {
    return metaDescription;
  }

  /**
   * @param metaDescription metaDescription or {@code null} for none
   */
  public Decor setMetaDescription(java.lang.String metaDescription) {
    this.metaDescription = metaDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMetaKeyword() {
    return metaKeyword;
  }

  /**
   * @param metaKeyword metaKeyword or {@code null} for none
   */
  public Decor setMetaKeyword(java.lang.String metaKeyword) {
    this.metaKeyword = metaKeyword;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSearchTitle() {
    return searchTitle;
  }

  /**
   * @param searchTitle searchTitle or {@code null} for none
   */
  public Decor setSearchTitle(java.lang.String searchTitle) {
    this.searchTitle = searchTitle;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSeourl() {
    return seourl;
  }

  /**
   * @param seourl seourl or {@code null} for none
   */
  public Decor setSeourl(java.lang.String seourl) {
    this.seourl = seourl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSource() {
    return source;
  }

  /**
   * @param source source or {@code null} for none
   */
  public Decor setSource(java.lang.String source) {
    this.source = source;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSourceUrl() {
    return sourceUrl;
  }

  /**
   * @param sourceUrl sourceUrl or {@code null} for none
   */
  public Decor setSourceUrl(java.lang.String sourceUrl) {
    this.sourceUrl = sourceUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public Decor setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<TimeLineStats> getTimeLineStates() {
    return timeLineStates;
  }

  /**
   * @param timeLineStates timeLineStates or {@code null} for none
   */
  public Decor setTimeLineStates(java.util.List<TimeLineStats> timeLineStates) {
    this.timeLineStates = timeLineStates;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public DecorItem getTitleSection() {
    return titleSection;
  }

  /**
   * @param titleSection titleSection or {@code null} for none
   */
  public Decor setTitleSection(DecorItem titleSection) {
    this.titleSection = titleSection;
    return this;
  }

  @Override
  public Decor set(String fieldName, Object value) {
    return (Decor) super.set(fieldName, value);
  }

  @Override
  public Decor clone() {
    return (Decor) super.clone();
  }

}
