/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2020-02-28 at 09:14:15 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.estimateEndPoint.model;

/**
 * Model definition for EstimationResult.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the estimateEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class EstimationResult extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float accuracyCustom;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String address;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer age;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean aiSet;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer bed;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float bspAI;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float bspCustom;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer floor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double latitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double longitude;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float size;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long time;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String type;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getAccuracyCustom() {
    return accuracyCustom;
  }

  /**
   * @param accuracyCustom accuracyCustom or {@code null} for none
   */
  public EstimationResult setAccuracyCustom(java.lang.Float accuracyCustom) {
    this.accuracyCustom = accuracyCustom;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAddress() {
    return address;
  }

  /**
   * @param address address or {@code null} for none
   */
  public EstimationResult setAddress(java.lang.String address) {
    this.address = address;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getAge() {
    return age;
  }

  /**
   * @param age age or {@code null} for none
   */
  public EstimationResult setAge(java.lang.Integer age) {
    this.age = age;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAiSet() {
    return aiSet;
  }

  /**
   * @param aiSet aiSet or {@code null} for none
   */
  public EstimationResult setAiSet(java.lang.Boolean aiSet) {
    this.aiSet = aiSet;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getBed() {
    return bed;
  }

  /**
   * @param bed bed or {@code null} for none
   */
  public EstimationResult setBed(java.lang.Integer bed) {
    this.bed = bed;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getBspAI() {
    return bspAI;
  }

  /**
   * @param bspAI bspAI or {@code null} for none
   */
  public EstimationResult setBspAI(java.lang.Float bspAI) {
    this.bspAI = bspAI;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getBspCustom() {
    return bspCustom;
  }

  /**
   * @param bspCustom bspCustom or {@code null} for none
   */
  public EstimationResult setBspCustom(java.lang.Float bspCustom) {
    this.bspCustom = bspCustom;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFloor() {
    return floor;
  }

  /**
   * @param floor floor or {@code null} for none
   */
  public EstimationResult setFloor(java.lang.Integer floor) {
    this.floor = floor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public EstimationResult setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLatitude() {
    return latitude;
  }

  /**
   * @param latitude latitude or {@code null} for none
   */
  public EstimationResult setLatitude(java.lang.Double latitude) {
    this.latitude = latitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLongitude() {
    return longitude;
  }

  /**
   * @param longitude longitude or {@code null} for none
   */
  public EstimationResult setLongitude(java.lang.Double longitude) {
    this.longitude = longitude;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getSize() {
    return size;
  }

  /**
   * @param size size or {@code null} for none
   */
  public EstimationResult setSize(java.lang.Float size) {
    this.size = size;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTime() {
    return time;
  }

  /**
   * @param time time or {@code null} for none
   */
  public EstimationResult setTime(java.lang.Long time) {
    this.time = time;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public EstimationResult setType(java.lang.String type) {
    this.type = type;
    return this;
  }

  @Override
  public EstimationResult set(String fieldName, Object value) {
    return (EstimationResult) super.set(fieldName, value);
  }

  @Override
  public EstimationResult clone() {
    return (EstimationResult) super.clone();
  }

}
