/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-11-29 at 11:12:27 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.propertyEndPoint.model;

/**
 * Model definition for LeadSourceWiseResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the propertyEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class LeadSourceWiseResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Integer errorId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String errorMessage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Integer registerUserAndroid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Integer registerUserIphone;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Integer registerUserWebsite;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<LeadSourceWiseConversion> sourceWiseConversions;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Boolean status;

  /**
   * @return value or {@code null} for none
   */
  public Integer getErrorId() {
    return errorId;
  }

  /**
   * @param errorId errorId or {@code null} for none
   */
  public LeadSourceWiseResponse setErrorId(Integer errorId) {
    this.errorId = errorId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getErrorMessage() {
    return errorMessage;
  }

  /**
   * @param errorMessage errorMessage or {@code null} for none
   */
  public LeadSourceWiseResponse setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public LeadSourceWiseResponse setId(Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Integer getRegisterUserAndroid() {
    return registerUserAndroid;
  }

  /**
   * @param registerUserAndroid registerUserAndroid or {@code null} for none
   */
  public LeadSourceWiseResponse setRegisterUserAndroid(Integer registerUserAndroid) {
    this.registerUserAndroid = registerUserAndroid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Integer getRegisterUserIphone() {
    return registerUserIphone;
  }

  /**
   * @param registerUserIphone registerUserIphone or {@code null} for none
   */
  public LeadSourceWiseResponse setRegisterUserIphone(Integer registerUserIphone) {
    this.registerUserIphone = registerUserIphone;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Integer getRegisterUserWebsite() {
    return registerUserWebsite;
  }

  /**
   * @param registerUserWebsite registerUserWebsite or {@code null} for none
   */
  public LeadSourceWiseResponse setRegisterUserWebsite(Integer registerUserWebsite) {
    this.registerUserWebsite = registerUserWebsite;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<LeadSourceWiseConversion> getSourceWiseConversions() {
    return sourceWiseConversions;
  }

  /**
   * @param sourceWiseConversions sourceWiseConversions or {@code null} for none
   */
  public LeadSourceWiseResponse setSourceWiseConversions(java.util.List<LeadSourceWiseConversion> sourceWiseConversions) {
    this.sourceWiseConversions = sourceWiseConversions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Boolean getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public LeadSourceWiseResponse setStatus(Boolean status) {
    this.status = status;
    return this;
  }

  @Override
  public LeadSourceWiseResponse set(String fieldName, Object value) {
    return (LeadSourceWiseResponse) super.set(fieldName, value);
  }

  @Override
  public LeadSourceWiseResponse clone() {
    return (LeadSourceWiseResponse) super.clone();
  }

}
