/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-11-29 at 11:12:27 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.propertyEndPoint.model;

/**
 * Model definition for UpdateProjectSCEORequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the propertyEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UpdateProjectSCEORequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String metaDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String metaKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String metaTitle;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String sceoURL;

  /**
   * @return value or {@code null} for none
   */
  public String getMetaDescription() {
    return metaDescription;
  }

  /**
   * @param metaDescription metaDescription or {@code null} for none
   */
  public UpdateProjectSCEORequest setMetaDescription(String metaDescription) {
    this.metaDescription = metaDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getMetaKey() {
    return metaKey;
  }

  /**
   * @param metaKey metaKey or {@code null} for none
   */
  public UpdateProjectSCEORequest setMetaKey(String metaKey) {
    this.metaKey = metaKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getMetaTitle() {
    return metaTitle;
  }

  /**
   * @param metaTitle metaTitle or {@code null} for none
   */
  public UpdateProjectSCEORequest setMetaTitle(String metaTitle) {
    this.metaTitle = metaTitle;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getSceoURL() {
    return sceoURL;
  }

  /**
   * @param sceoURL sceoURL or {@code null} for none
   */
  public UpdateProjectSCEORequest setSceoURL(String sceoURL) {
    this.sceoURL = sceoURL;
    return this;
  }

  @Override
  public UpdateProjectSCEORequest set(String fieldName, Object value) {
    return (UpdateProjectSCEORequest) super.set(fieldName, value);
  }

  @Override
  public UpdateProjectSCEORequest clone() {
    return (UpdateProjectSCEORequest) super.clone();
  }

}
