/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-11-29 at 11:12:27 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.propertyEndPoint.model;

/**
 * Model definition for UpdateProjectRMResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the propertyEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UpdateProjectRMResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Integer errorId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String errorMessage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Lead lead;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Boolean status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Task task;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long uid;

  /**
   * @return value or {@code null} for none
   */
  public Integer getErrorId() {
    return errorId;
  }

  /**
   * @param errorId errorId or {@code null} for none
   */
  public UpdateProjectRMResponse setErrorId(Integer errorId) {
    this.errorId = errorId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getErrorMessage() {
    return errorMessage;
  }

  /**
   * @param errorMessage errorMessage or {@code null} for none
   */
  public UpdateProjectRMResponse setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public UpdateProjectRMResponse setId(Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Lead getLead() {
    return lead;
  }

  /**
   * @param lead lead or {@code null} for none
   */
  public UpdateProjectRMResponse setLead(Lead lead) {
    this.lead = lead;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Boolean getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public UpdateProjectRMResponse setStatus(Boolean status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Task getTask() {
    return task;
  }

  /**
   * @param task task or {@code null} for none
   */
  public UpdateProjectRMResponse setTask(Task task) {
    this.task = task;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Long getUid() {
    return uid;
  }

  /**
   * @param uid uid or {@code null} for none
   */
  public UpdateProjectRMResponse setUid(Long uid) {
    this.uid = uid;
    return this;
  }

  @Override
  public UpdateProjectRMResponse set(String fieldName, Object value) {
    return (UpdateProjectRMResponse) super.set(fieldName, value);
  }

  @Override
  public UpdateProjectRMResponse clone() {
    return (UpdateProjectRMResponse) super.clone();
  }

}
