/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-09-26 19:19:48 UTC)
 * on 2017-10-10 at 06:54:35 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.newsEndPoint;

/**
 * Service definition for NewsEndPoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link NewsEndPointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class NewsEndPoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.23.0 of the newsEndPoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://housingtestserver.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "newsEndPoint/v1/";

  /**
   * The default encoded batch path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.23
   */
  public static final String DEFAULT_BATCH_PATH = "batch";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public NewsEndPoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  NewsEndPoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "addNews".
   *
   * This request holds the parameters needed by the newsEndPoint server.  After setting any optional
   * parameters, call the {@link AddNews#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param token
   * @param content the {@link com.buy.housing.backend.newsEndPoint.model.News}
   * @return the request
   */
  public AddNews addNews(Long id, String token, com.buy.housing.backend.newsEndPoint.model.News content) throws java.io.IOException {
    AddNews result = new AddNews(id, token, content);
    initialize(result);
    return result;
  }

  public class AddNews extends NewsEndPointRequest<com.buy.housing.backend.newsEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "addNews/{Id}/{token}";

    /**
     * Create a request for the method "addNews".
     *
     * This request holds the parameters needed by the the newsEndPoint server.  After setting any
     * optional parameters, call the {@link AddNews#execute()} method to invoke the remote operation.
     * <p> {@link
     * AddNews#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param token
     * @param content the {@link com.buy.housing.backend.newsEndPoint.model.News}
     * @since 1.13
     */
    protected AddNews(Long id, String token, com.buy.housing.backend.newsEndPoint.model.News content) {
      super(NewsEndPoint.this, "POST", REST_PATH, content, com.buy.housing.backend.newsEndPoint.model.CommonResponse.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
    }

    @Override
    public AddNews setAlt(String alt) {
      return (AddNews) super.setAlt(alt);
    }

    @Override
    public AddNews setFields(String fields) {
      return (AddNews) super.setFields(fields);
    }

    @Override
    public AddNews setKey(String key) {
      return (AddNews) super.setKey(key);
    }

    @Override
    public AddNews setOauthToken(String oauthToken) {
      return (AddNews) super.setOauthToken(oauthToken);
    }

    @Override
    public AddNews setPrettyPrint(Boolean prettyPrint) {
      return (AddNews) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddNews setQuotaUser(String quotaUser) {
      return (AddNews) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddNews setUserIp(String userIp) {
      return (AddNews) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key("Id")
    private Long id;

    /**

     */
    public Long getId() {
      return id;
    }

    public AddNews setId(Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private String token;

    /**

     */
    public String getToken() {
      return token;
    }

    public AddNews setToken(String token) {
      this.token = token;
      return this;
    }

    @Override
    public AddNews set(String parameterName, Object value) {
      return (AddNews) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "deleteNews".
   *
   * This request holds the parameters needed by the newsEndPoint server.  After setting any optional
   * parameters, call the {@link DeleteNews#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param token
   * @param content the {@link com.buy.housing.backend.newsEndPoint.model.News}
   * @return the request
   */
  public DeleteNews deleteNews(Long id, String token, com.buy.housing.backend.newsEndPoint.model.News content) throws java.io.IOException {
    DeleteNews result = new DeleteNews(id, token, content);
    initialize(result);
    return result;
  }

  public class DeleteNews extends NewsEndPointRequest<com.buy.housing.backend.newsEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "news/{Id}/{token}";

    /**
     * Create a request for the method "deleteNews".
     *
     * This request holds the parameters needed by the the newsEndPoint server.  After setting any
     * optional parameters, call the {@link DeleteNews#execute()} method to invoke the remote
     * operation. <p> {@link
     * DeleteNews#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param token
     * @param content the {@link com.buy.housing.backend.newsEndPoint.model.News}
     * @since 1.13
     */
    protected DeleteNews(Long id, String token, com.buy.housing.backend.newsEndPoint.model.News content) {
      super(NewsEndPoint.this, "POST", REST_PATH, content, com.buy.housing.backend.newsEndPoint.model.CommonResponse.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
    }

    @Override
    public DeleteNews setAlt(String alt) {
      return (DeleteNews) super.setAlt(alt);
    }

    @Override
    public DeleteNews setFields(String fields) {
      return (DeleteNews) super.setFields(fields);
    }

    @Override
    public DeleteNews setKey(String key) {
      return (DeleteNews) super.setKey(key);
    }

    @Override
    public DeleteNews setOauthToken(String oauthToken) {
      return (DeleteNews) super.setOauthToken(oauthToken);
    }

    @Override
    public DeleteNews setPrettyPrint(Boolean prettyPrint) {
      return (DeleteNews) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public DeleteNews setQuotaUser(String quotaUser) {
      return (DeleteNews) super.setQuotaUser(quotaUser);
    }

    @Override
    public DeleteNews setUserIp(String userIp) {
      return (DeleteNews) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key("Id")
    private Long id;

    /**

     */
    public Long getId() {
      return id;
    }

    public DeleteNews setId(Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private String token;

    /**

     */
    public String getToken() {
      return token;
    }

    public DeleteNews setToken(String token) {
      this.token = token;
      return this;
    }

    @Override
    public DeleteNews set(String parameterName, Object value) {
      return (DeleteNews) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getNewsList".
   *
   * This request holds the parameters needed by the newsEndPoint server.  After setting any optional
   * parameters, call the {@link GetNewsList#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param token
   * @param offset
   * @param limit
   * @return the request
   */
  public GetNewsList getNewsList(Long id, String token, Integer offset, Integer limit) throws java.io.IOException {
    GetNewsList result = new GetNewsList(id, token, offset, limit);
    initialize(result);
    return result;
  }

  public class GetNewsList extends NewsEndPointRequest<com.buy.housing.backend.newsEndPoint.model.NewsListResponse> {

    private static final String REST_PATH = "newslistresponse/{Id}/{token}/{offset}/{limit}";

    /**
     * Create a request for the method "getNewsList".
     *
     * This request holds the parameters needed by the the newsEndPoint server.  After setting any
     * optional parameters, call the {@link GetNewsList#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetNewsList#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param token
     * @param offset
     * @param limit
     * @since 1.13
     */
    protected GetNewsList(Long id, String token, Integer offset, Integer limit) {
      super(NewsEndPoint.this, "GET", REST_PATH, null, com.buy.housing.backend.newsEndPoint.model.NewsListResponse.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
      this.offset = com.google.api.client.util.Preconditions.checkNotNull(offset, "Required parameter offset must be specified.");
      this.limit = com.google.api.client.util.Preconditions.checkNotNull(limit, "Required parameter limit must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetNewsList setAlt(String alt) {
      return (GetNewsList) super.setAlt(alt);
    }

    @Override
    public GetNewsList setFields(String fields) {
      return (GetNewsList) super.setFields(fields);
    }

    @Override
    public GetNewsList setKey(String key) {
      return (GetNewsList) super.setKey(key);
    }

    @Override
    public GetNewsList setOauthToken(String oauthToken) {
      return (GetNewsList) super.setOauthToken(oauthToken);
    }

    @Override
    public GetNewsList setPrettyPrint(Boolean prettyPrint) {
      return (GetNewsList) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetNewsList setQuotaUser(String quotaUser) {
      return (GetNewsList) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetNewsList setUserIp(String userIp) {
      return (GetNewsList) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key("Id")
    private Long id;

    /**

     */
    public Long getId() {
      return id;
    }

    public GetNewsList setId(Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private String token;

    /**

     */
    public String getToken() {
      return token;
    }

    public GetNewsList setToken(String token) {
      this.token = token;
      return this;
    }

    @com.google.api.client.util.Key
    private Integer offset;

    /**

     */
    public Integer getOffset() {
      return offset;
    }

    public GetNewsList setOffset(Integer offset) {
      this.offset = offset;
      return this;
    }

    @com.google.api.client.util.Key
    private Integer limit;

    /**

     */
    public Integer getLimit() {
      return limit;
    }

    public GetNewsList setLimit(Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public GetNewsList set(String parameterName, Object value) {
      return (GetNewsList) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link NewsEndPoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
      //setBatchPath(DEFAULT_BATCH_PATH);
    }

    /** Builds a new instance of {@link NewsEndPoint}. */
    @Override
    public NewsEndPoint build() {
      return new NewsEndPoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    /*@Override
    public Builder setBatchPath(String batchPath) {
      return (Builder) super.setBatchPath(batchPath);
    }*/

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link NewsEndPointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setNewsEndPointRequestInitializer(
        NewsEndPointRequestInitializer newsendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(newsendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
