/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-04-23 at 05:46:42 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.userEndPoint.model;

/**
 * Model definition for AppConfig.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the userEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppConfig extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float alarmEndTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float alarmStartTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer checkInDist;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String contactNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer enquiryPendingTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean geoTracking;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float interestRate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer locationCollectionInterval;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer locationUpdateInterval;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer mapPrjRefreshDist;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer mapProjectCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer rangeCheckOutTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer snoozeTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer taskRefreshTimeInSec;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getAlarmEndTime() {
    return alarmEndTime;
  }

  /**
   * @param alarmEndTime alarmEndTime or {@code null} for none
   */
  public AppConfig setAlarmEndTime(java.lang.Float alarmEndTime) {
    this.alarmEndTime = alarmEndTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getAlarmStartTime() {
    return alarmStartTime;
  }

  /**
   * @param alarmStartTime alarmStartTime or {@code null} for none
   */
  public AppConfig setAlarmStartTime(java.lang.Float alarmStartTime) {
    this.alarmStartTime = alarmStartTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getCheckInDist() {
    return checkInDist;
  }

  /**
   * @param checkInDist checkInDist or {@code null} for none
   */
  public AppConfig setCheckInDist(java.lang.Integer checkInDist) {
    this.checkInDist = checkInDist;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getContactNumber() {
    return contactNumber;
  }

  /**
   * @param contactNumber contactNumber or {@code null} for none
   */
  public AppConfig setContactNumber(java.lang.String contactNumber) {
    this.contactNumber = contactNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getEnquiryPendingTime() {
    return enquiryPendingTime;
  }

  /**
   * @param enquiryPendingTime enquiryPendingTime or {@code null} for none
   */
  public AppConfig setEnquiryPendingTime(java.lang.Integer enquiryPendingTime) {
    this.enquiryPendingTime = enquiryPendingTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getGeoTracking() {
    return geoTracking;
  }

  /**
   * @param geoTracking geoTracking or {@code null} for none
   */
  public AppConfig setGeoTracking(java.lang.Boolean geoTracking) {
    this.geoTracking = geoTracking;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public AppConfig setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getInterestRate() {
    return interestRate;
  }

  /**
   * @param interestRate interestRate or {@code null} for none
   */
  public AppConfig setInterestRate(java.lang.Float interestRate) {
    this.interestRate = interestRate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLocationCollectionInterval() {
    return locationCollectionInterval;
  }

  /**
   * @param locationCollectionInterval locationCollectionInterval or {@code null} for none
   */
  public AppConfig setLocationCollectionInterval(java.lang.Integer locationCollectionInterval) {
    this.locationCollectionInterval = locationCollectionInterval;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLocationUpdateInterval() {
    return locationUpdateInterval;
  }

  /**
   * @param locationUpdateInterval locationUpdateInterval or {@code null} for none
   */
  public AppConfig setLocationUpdateInterval(java.lang.Integer locationUpdateInterval) {
    this.locationUpdateInterval = locationUpdateInterval;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMapPrjRefreshDist() {
    return mapPrjRefreshDist;
  }

  /**
   * @param mapPrjRefreshDist mapPrjRefreshDist or {@code null} for none
   */
  public AppConfig setMapPrjRefreshDist(java.lang.Integer mapPrjRefreshDist) {
    this.mapPrjRefreshDist = mapPrjRefreshDist;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getMapProjectCount() {
    return mapProjectCount;
  }

  /**
   * @param mapProjectCount mapProjectCount or {@code null} for none
   */
  public AppConfig setMapProjectCount(java.lang.Integer mapProjectCount) {
    this.mapProjectCount = mapProjectCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getRangeCheckOutTime() {
    return rangeCheckOutTime;
  }

  /**
   * @param rangeCheckOutTime rangeCheckOutTime or {@code null} for none
   */
  public AppConfig setRangeCheckOutTime(java.lang.Integer rangeCheckOutTime) {
    this.rangeCheckOutTime = rangeCheckOutTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getSnoozeTime() {
    return snoozeTime;
  }

  /**
   * @param snoozeTime snoozeTime or {@code null} for none
   */
  public AppConfig setSnoozeTime(java.lang.Integer snoozeTime) {
    this.snoozeTime = snoozeTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTaskRefreshTimeInSec() {
    return taskRefreshTimeInSec;
  }

  /**
   * @param taskRefreshTimeInSec taskRefreshTimeInSec or {@code null} for none
   */
  public AppConfig setTaskRefreshTimeInSec(java.lang.Integer taskRefreshTimeInSec) {
    this.taskRefreshTimeInSec = taskRefreshTimeInSec;
    return this;
  }

  @Override
  public AppConfig set(String fieldName, Object value) {
    return (AppConfig) super.set(fieldName, value);
  }

  @Override
  public AppConfig clone() {
    return (AppConfig) super.clone();
  }

}
