/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-04-23 at 05:46:42 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.userEndPoint.model;

/**
 * Model definition for Bank.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the userEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Bank extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String bankCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String bankSalesType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float commission;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Contact> contactList;

  static {
    // hack to force ProGuard to consider Contact used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(Contact.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float interest;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String interestType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Document> mouDocs;

  static {
    // hack to force ProGuard to consider Document used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(Document.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long mouExpiry;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<KeyValuePair> offersList;

  static {
    // hack to force ProGuard to consider KeyValuePair used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(KeyValuePair.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String searchNameInUp;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBankCode() {
    return bankCode;
  }

  /**
   * @param bankCode bankCode or {@code null} for none
   */
  public Bank setBankCode(java.lang.String bankCode) {
    this.bankCode = bankCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBankSalesType() {
    return bankSalesType;
  }

  /**
   * @param bankSalesType bankSalesType or {@code null} for none
   */
  public Bank setBankSalesType(java.lang.String bankSalesType) {
    this.bankSalesType = bankSalesType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getCommission() {
    return commission;
  }

  /**
   * @param commission commission or {@code null} for none
   */
  public Bank setCommission(java.lang.Float commission) {
    this.commission = commission;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Contact> getContactList() {
    return contactList;
  }

  /**
   * @param contactList contactList or {@code null} for none
   */
  public Bank setContactList(java.util.List<Contact> contactList) {
    this.contactList = contactList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Bank setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getInterest() {
    return interest;
  }

  /**
   * @param interest interest or {@code null} for none
   */
  public Bank setInterest(java.lang.Float interest) {
    this.interest = interest;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInterestType() {
    return interestType;
  }

  /**
   * @param interestType interestType or {@code null} for none
   */
  public Bank setInterestType(java.lang.String interestType) {
    this.interestType = interestType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLogo() {
    return logo;
  }

  /**
   * @param logo logo or {@code null} for none
   */
  public Bank setLogo(java.lang.String logo) {
    this.logo = logo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Document> getMouDocs() {
    return mouDocs;
  }

  /**
   * @param mouDocs mouDocs or {@code null} for none
   */
  public Bank setMouDocs(java.util.List<Document> mouDocs) {
    this.mouDocs = mouDocs;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getMouExpiry() {
    return mouExpiry;
  }

  /**
   * @param mouExpiry mouExpiry or {@code null} for none
   */
  public Bank setMouExpiry(java.lang.Long mouExpiry) {
    this.mouExpiry = mouExpiry;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Bank setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<KeyValuePair> getOffersList() {
    return offersList;
  }

  /**
   * @param offersList offersList or {@code null} for none
   */
  public Bank setOffersList(java.util.List<KeyValuePair> offersList) {
    this.offersList = offersList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSearchNameInUp() {
    return searchNameInUp;
  }

  /**
   * @param searchNameInUp searchNameInUp or {@code null} for none
   */
  public Bank setSearchNameInUp(java.lang.String searchNameInUp) {
    this.searchNameInUp = searchNameInUp;
    return this;
  }

  @Override
  public Bank set(String fieldName, Object value) {
    return (Bank) super.set(fieldName, value);
  }

  @Override
  public Bank clone() {
    return (Bank) super.clone();
  }

}
