/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-04-23 at 05:46:42 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.userEndPoint.model;

/**
 * Model definition for GetMyPropertyListResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the userEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GetMyPropertyListResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Customer> customerList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer errorId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String errorMessage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<LoanLead> loanLeadList;

  static {
    // hack to force ProGuard to consider LoanLead used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(LoanLead.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<PropertyBooking> propertyBookingList;

  static {
    // hack to force ProGuard to consider PropertyBooking used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(PropertyBooking.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<PropertyType> propertyTypeList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<PropertyUnit> propertyUnitList;

  static {
    // hack to force ProGuard to consider PropertyUnit used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(PropertyUnit.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean status;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Customer> getCustomerList() {
    return customerList;
  }

  /**
   * @param customerList customerList or {@code null} for none
   */
  public GetMyPropertyListResponse setCustomerList(java.util.List<Customer> customerList) {
    this.customerList = customerList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getErrorId() {
    return errorId;
  }

  /**
   * @param errorId errorId or {@code null} for none
   */
  public GetMyPropertyListResponse setErrorId(java.lang.Integer errorId) {
    this.errorId = errorId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getErrorMessage() {
    return errorMessage;
  }

  /**
   * @param errorMessage errorMessage or {@code null} for none
   */
  public GetMyPropertyListResponse setErrorMessage(java.lang.String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<LoanLead> getLoanLeadList() {
    return loanLeadList;
  }

  /**
   * @param loanLeadList loanLeadList or {@code null} for none
   */
  public GetMyPropertyListResponse setLoanLeadList(java.util.List<LoanLead> loanLeadList) {
    this.loanLeadList = loanLeadList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<PropertyBooking> getPropertyBookingList() {
    return propertyBookingList;
  }

  /**
   * @param propertyBookingList propertyBookingList or {@code null} for none
   */
  public GetMyPropertyListResponse setPropertyBookingList(java.util.List<PropertyBooking> propertyBookingList) {
    this.propertyBookingList = propertyBookingList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<PropertyType> getPropertyTypeList() {
    return propertyTypeList;
  }

  /**
   * @param propertyTypeList propertyTypeList or {@code null} for none
   */
  public GetMyPropertyListResponse setPropertyTypeList(java.util.List<PropertyType> propertyTypeList) {
    this.propertyTypeList = propertyTypeList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<PropertyUnit> getPropertyUnitList() {
    return propertyUnitList;
  }

  /**
   * @param propertyUnitList propertyUnitList or {@code null} for none
   */
  public GetMyPropertyListResponse setPropertyUnitList(java.util.List<PropertyUnit> propertyUnitList) {
    this.propertyUnitList = propertyUnitList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public GetMyPropertyListResponse setStatus(java.lang.Boolean status) {
    this.status = status;
    return this;
  }

  @Override
  public GetMyPropertyListResponse set(String fieldName, Object value) {
    return (GetMyPropertyListResponse) super.set(fieldName, value);
  }

  @Override
  public GetMyPropertyListResponse clone() {
    return (GetMyPropertyListResponse) super.clone();
  }

}
