/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-04-23 at 05:46:42 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.userEndPoint.model;

/**
 * Model definition for Project.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the userEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Project extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String accName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String accNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String address;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> agentList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Amenity> amenities;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Image> amenityImages;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String areaUnit;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Bank> bankLoan;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String bankName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Image> bannerImages;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> blockList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String branchName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String bspRange;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long builderId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String builderName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String builderNameInUp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String city;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long cityId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<FloorPlan> clusterPlan;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<CommisionSlab> collectionSlabList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String commisionRemarks;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<CommisionSlab> commisionSlabList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float connectivityScore;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Image> constructionImages;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String country;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String coverImage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Contact> devContactList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String developerIncentive;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Document> documents;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private DriveView driveView;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private DriveView droneView;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long endDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long endOfferDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean exclusive;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean expire;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fdi;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float greenArea;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String hallipad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<KeyValuePair> htmlList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ifsc;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Image> images;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String internalIncentive;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double lat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long launchDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float lifeStyleScore;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float livabilityScore;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double lng;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String locality;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private FloorPlan locationPlan;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logoImageURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String metaDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String metaKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String metaTitle;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Document> mouDocumentList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mouURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Nearby> nearby;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Image> neighbourImages;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String newsUpdate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> noteList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numberOfBuilderFloor;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numberOfPlots;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numberOfShops;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numberOfUnits;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numberOfVillas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numberofMultiStoryTowers;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String offer;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean offerAvailable;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String offerLink;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long onBoardingDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Image> otherImages;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<PaymentPlan> paymentPlanList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String phone;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pinCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<KeyValuePair> plcDescriptionList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> plcList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long possessionDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long preLaunchDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String priceRange;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<PriceTrend> priceTrends;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String projectArchitect;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String projectStatus;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String projectSummary;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String projectType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String projectbrowcherPdfURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String propertyTypeJson;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.util.List<java.lang.Long> propertyTypeList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String propertyTypeRange;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String reraId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long rmagentId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String rmagentName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String rmagentPhone;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sCoverImage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float safetyScore;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sceoURL;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String searchNameInUp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private FloorPlan sitePlan;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sizeRange;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long startDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long startOfferDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String state;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long targetAmount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean tentative;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float totalArea;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer totalNumberBlock;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float valueForMoneyScore;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Video> videos;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String walkThroughVideoURL;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAccName() {
    return accName;
  }

  /**
   * @param accName accName or {@code null} for none
   */
  public Project setAccName(java.lang.String accName) {
    this.accName = accName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAccNumber() {
    return accNumber;
  }

  /**
   * @param accNumber accNumber or {@code null} for none
   */
  public Project setAccNumber(java.lang.String accNumber) {
    this.accNumber = accNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAddress() {
    return address;
  }

  /**
   * @param address address or {@code null} for none
   */
  public Project setAddress(java.lang.String address) {
    this.address = address;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getAgentList() {
    return agentList;
  }

  /**
   * @param agentList agentList or {@code null} for none
   */
  public Project setAgentList(java.util.List<java.lang.Long> agentList) {
    this.agentList = agentList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Amenity> getAmenities() {
    return amenities;
  }

  /**
   * @param amenities amenities or {@code null} for none
   */
  public Project setAmenities(java.util.List<Amenity> amenities) {
    this.amenities = amenities;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Image> getAmenityImages() {
    return amenityImages;
  }

  /**
   * @param amenityImages amenityImages or {@code null} for none
   */
  public Project setAmenityImages(java.util.List<Image> amenityImages) {
    this.amenityImages = amenityImages;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAreaUnit() {
    return areaUnit;
  }

  /**
   * @param areaUnit areaUnit or {@code null} for none
   */
  public Project setAreaUnit(java.lang.String areaUnit) {
    this.areaUnit = areaUnit;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Bank> getBankLoan() {
    return bankLoan;
  }

  /**
   * @param bankLoan bankLoan or {@code null} for none
   */
  public Project setBankLoan(java.util.List<Bank> bankLoan) {
    this.bankLoan = bankLoan;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBankName() {
    return bankName;
  }

  /**
   * @param bankName bankName or {@code null} for none
   */
  public Project setBankName(java.lang.String bankName) {
    this.bankName = bankName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Image> getBannerImages() {
    return bannerImages;
  }

  /**
   * @param bannerImages bannerImages or {@code null} for none
   */
  public Project setBannerImages(java.util.List<Image> bannerImages) {
    this.bannerImages = bannerImages;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getBlockList() {
    return blockList;
  }

  /**
   * @param blockList blockList or {@code null} for none
   */
  public Project setBlockList(java.util.List<java.lang.Long> blockList) {
    this.blockList = blockList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBranchName() {
    return branchName;
  }

  /**
   * @param branchName branchName or {@code null} for none
   */
  public Project setBranchName(java.lang.String branchName) {
    this.branchName = branchName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBspRange() {
    return bspRange;
  }

  /**
   * @param bspRange bspRange or {@code null} for none
   */
  public Project setBspRange(java.lang.String bspRange) {
    this.bspRange = bspRange;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getBuilderId() {
    return builderId;
  }

  /**
   * @param builderId builderId or {@code null} for none
   */
  public Project setBuilderId(java.lang.Long builderId) {
    this.builderId = builderId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBuilderName() {
    return builderName;
  }

  /**
   * @param builderName builderName or {@code null} for none
   */
  public Project setBuilderName(java.lang.String builderName) {
    this.builderName = builderName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getBuilderNameInUp() {
    return builderNameInUp;
  }

  /**
   * @param builderNameInUp builderNameInUp or {@code null} for none
   */
  public Project setBuilderNameInUp(java.lang.String builderNameInUp) {
    this.builderNameInUp = builderNameInUp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCity() {
    return city;
  }

  /**
   * @param city city or {@code null} for none
   */
  public Project setCity(java.lang.String city) {
    this.city = city;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCityId() {
    return cityId;
  }

  /**
   * @param cityId cityId or {@code null} for none
   */
  public Project setCityId(java.lang.Long cityId) {
    this.cityId = cityId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<FloorPlan> getClusterPlan() {
    return clusterPlan;
  }

  /**
   * @param clusterPlan clusterPlan or {@code null} for none
   */
  public Project setClusterPlan(java.util.List<FloorPlan> clusterPlan) {
    this.clusterPlan = clusterPlan;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<CommisionSlab> getCollectionSlabList() {
    return collectionSlabList;
  }

  /**
   * @param collectionSlabList collectionSlabList or {@code null} for none
   */
  public Project setCollectionSlabList(java.util.List<CommisionSlab> collectionSlabList) {
    this.collectionSlabList = collectionSlabList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCommisionRemarks() {
    return commisionRemarks;
  }

  /**
   * @param commisionRemarks commisionRemarks or {@code null} for none
   */
  public Project setCommisionRemarks(java.lang.String commisionRemarks) {
    this.commisionRemarks = commisionRemarks;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<CommisionSlab> getCommisionSlabList() {
    return commisionSlabList;
  }

  /**
   * @param commisionSlabList commisionSlabList or {@code null} for none
   */
  public Project setCommisionSlabList(java.util.List<CommisionSlab> commisionSlabList) {
    this.commisionSlabList = commisionSlabList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getConnectivityScore() {
    return connectivityScore;
  }

  /**
   * @param connectivityScore connectivityScore or {@code null} for none
   */
  public Project setConnectivityScore(java.lang.Float connectivityScore) {
    this.connectivityScore = connectivityScore;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Image> getConstructionImages() {
    return constructionImages;
  }

  /**
   * @param constructionImages constructionImages or {@code null} for none
   */
  public Project setConstructionImages(java.util.List<Image> constructionImages) {
    this.constructionImages = constructionImages;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCountry() {
    return country;
  }

  /**
   * @param country country or {@code null} for none
   */
  public Project setCountry(java.lang.String country) {
    this.country = country;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCoverImage() {
    return coverImage;
  }

  /**
   * @param coverImage coverImage or {@code null} for none
   */
  public Project setCoverImage(java.lang.String coverImage) {
    this.coverImage = coverImage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Contact> getDevContactList() {
    return devContactList;
  }

  /**
   * @param devContactList devContactList or {@code null} for none
   */
  public Project setDevContactList(java.util.List<Contact> devContactList) {
    this.devContactList = devContactList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeveloperIncentive() {
    return developerIncentive;
  }

  /**
   * @param developerIncentive developerIncentive or {@code null} for none
   */
  public Project setDeveloperIncentive(java.lang.String developerIncentive) {
    this.developerIncentive = developerIncentive;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Document> getDocuments() {
    return documents;
  }

  /**
   * @param documents documents or {@code null} for none
   */
  public Project setDocuments(java.util.List<Document> documents) {
    this.documents = documents;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public DriveView getDriveView() {
    return driveView;
  }

  /**
   * @param driveView driveView or {@code null} for none
   */
  public Project setDriveView(DriveView driveView) {
    this.driveView = driveView;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public DriveView getDroneView() {
    return droneView;
  }

  /**
   * @param droneView droneView or {@code null} for none
   */
  public Project setDroneView(DriveView droneView) {
    this.droneView = droneView;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getEndDate() {
    return endDate;
  }

  /**
   * @param endDate endDate or {@code null} for none
   */
  public Project setEndDate(java.lang.Long endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getEndOfferDate() {
    return endOfferDate;
  }

  /**
   * @param endOfferDate endOfferDate or {@code null} for none
   */
  public Project setEndOfferDate(java.lang.Long endOfferDate) {
    this.endOfferDate = endOfferDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getExclusive() {
    return exclusive;
  }

  /**
   * @param exclusive exclusive or {@code null} for none
   */
  public Project setExclusive(java.lang.Boolean exclusive) {
    this.exclusive = exclusive;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getExpire() {
    return expire;
  }

  /**
   * @param expire expire or {@code null} for none
   */
  public Project setExpire(java.lang.Boolean expire) {
    this.expire = expire;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFdi() {
    return fdi;
  }

  /**
   * @param fdi fdi or {@code null} for none
   */
  public Project setFdi(java.lang.String fdi) {
    this.fdi = fdi;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getGreenArea() {
    return greenArea;
  }

  /**
   * @param greenArea greenArea or {@code null} for none
   */
  public Project setGreenArea(java.lang.Float greenArea) {
    this.greenArea = greenArea;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHallipad() {
    return hallipad;
  }

  /**
   * @param hallipad hallipad or {@code null} for none
   */
  public Project setHallipad(java.lang.String hallipad) {
    this.hallipad = hallipad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<KeyValuePair> getHtmlList() {
    return htmlList;
  }

  /**
   * @param htmlList htmlList or {@code null} for none
   */
  public Project setHtmlList(java.util.List<KeyValuePair> htmlList) {
    this.htmlList = htmlList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Project setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIfsc() {
    return ifsc;
  }

  /**
   * @param ifsc ifsc or {@code null} for none
   */
  public Project setIfsc(java.lang.String ifsc) {
    this.ifsc = ifsc;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Image> getImages() {
    return images;
  }

  /**
   * @param images images or {@code null} for none
   */
  public Project setImages(java.util.List<Image> images) {
    this.images = images;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getInternalIncentive() {
    return internalIncentive;
  }

  /**
   * @param internalIncentive internalIncentive or {@code null} for none
   */
  public Project setInternalIncentive(java.lang.String internalIncentive) {
    this.internalIncentive = internalIncentive;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLat() {
    return lat;
  }

  /**
   * @param lat lat or {@code null} for none
   */
  public Project setLat(java.lang.Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getLaunchDate() {
    return launchDate;
  }

  /**
   * @param launchDate launchDate or {@code null} for none
   */
  public Project setLaunchDate(java.lang.Long launchDate) {
    this.launchDate = launchDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLifeStyleScore() {
    return lifeStyleScore;
  }

  /**
   * @param lifeStyleScore lifeStyleScore or {@code null} for none
   */
  public Project setLifeStyleScore(java.lang.Float lifeStyleScore) {
    this.lifeStyleScore = lifeStyleScore;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getLivabilityScore() {
    return livabilityScore;
  }

  /**
   * @param livabilityScore livabilityScore or {@code null} for none
   */
  public Project setLivabilityScore(java.lang.Float livabilityScore) {
    this.livabilityScore = livabilityScore;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLng() {
    return lng;
  }

  /**
   * @param lng lng or {@code null} for none
   */
  public Project setLng(java.lang.Double lng) {
    this.lng = lng;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLocality() {
    return locality;
  }

  /**
   * @param locality locality or {@code null} for none
   */
  public Project setLocality(java.lang.String locality) {
    this.locality = locality;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public FloorPlan getLocationPlan() {
    return locationPlan;
  }

  /**
   * @param locationPlan locationPlan or {@code null} for none
   */
  public Project setLocationPlan(FloorPlan locationPlan) {
    this.locationPlan = locationPlan;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLogoImageURL() {
    return logoImageURL;
  }

  /**
   * @param logoImageURL logoImageURL or {@code null} for none
   */
  public Project setLogoImageURL(java.lang.String logoImageURL) {
    this.logoImageURL = logoImageURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMetaDescription() {
    return metaDescription;
  }

  /**
   * @param metaDescription metaDescription or {@code null} for none
   */
  public Project setMetaDescription(java.lang.String metaDescription) {
    this.metaDescription = metaDescription;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMetaKey() {
    return metaKey;
  }

  /**
   * @param metaKey metaKey or {@code null} for none
   */
  public Project setMetaKey(java.lang.String metaKey) {
    this.metaKey = metaKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMetaTitle() {
    return metaTitle;
  }

  /**
   * @param metaTitle metaTitle or {@code null} for none
   */
  public Project setMetaTitle(java.lang.String metaTitle) {
    this.metaTitle = metaTitle;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Document> getMouDocumentList() {
    return mouDocumentList;
  }

  /**
   * @param mouDocumentList mouDocumentList or {@code null} for none
   */
  public Project setMouDocumentList(java.util.List<Document> mouDocumentList) {
    this.mouDocumentList = mouDocumentList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMouURL() {
    return mouURL;
  }

  /**
   * @param mouURL mouURL or {@code null} for none
   */
  public Project setMouURL(java.lang.String mouURL) {
    this.mouURL = mouURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Project setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Nearby> getNearby() {
    return nearby;
  }

  /**
   * @param nearby nearby or {@code null} for none
   */
  public Project setNearby(java.util.List<Nearby> nearby) {
    this.nearby = nearby;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Image> getNeighbourImages() {
    return neighbourImages;
  }

  /**
   * @param neighbourImages neighbourImages or {@code null} for none
   */
  public Project setNeighbourImages(java.util.List<Image> neighbourImages) {
    this.neighbourImages = neighbourImages;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNewsUpdate() {
    return newsUpdate;
  }

  /**
   * @param newsUpdate newsUpdate or {@code null} for none
   */
  public Project setNewsUpdate(java.lang.String newsUpdate) {
    this.newsUpdate = newsUpdate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getNoteList() {
    return noteList;
  }

  /**
   * @param noteList noteList or {@code null} for none
   */
  public Project setNoteList(java.util.List<java.lang.String> noteList) {
    this.noteList = noteList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumberOfBuilderFloor() {
    return numberOfBuilderFloor;
  }

  /**
   * @param numberOfBuilderFloor numberOfBuilderFloor or {@code null} for none
   */
  public Project setNumberOfBuilderFloor(java.lang.Integer numberOfBuilderFloor) {
    this.numberOfBuilderFloor = numberOfBuilderFloor;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumberOfPlots() {
    return numberOfPlots;
  }

  /**
   * @param numberOfPlots numberOfPlots or {@code null} for none
   */
  public Project setNumberOfPlots(java.lang.Integer numberOfPlots) {
    this.numberOfPlots = numberOfPlots;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumberOfShops() {
    return numberOfShops;
  }

  /**
   * @param numberOfShops numberOfShops or {@code null} for none
   */
  public Project setNumberOfShops(java.lang.Integer numberOfShops) {
    this.numberOfShops = numberOfShops;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumberOfUnits() {
    return numberOfUnits;
  }

  /**
   * @param numberOfUnits numberOfUnits or {@code null} for none
   */
  public Project setNumberOfUnits(java.lang.Integer numberOfUnits) {
    this.numberOfUnits = numberOfUnits;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumberOfVillas() {
    return numberOfVillas;
  }

  /**
   * @param numberOfVillas numberOfVillas or {@code null} for none
   */
  public Project setNumberOfVillas(java.lang.Integer numberOfVillas) {
    this.numberOfVillas = numberOfVillas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumberofMultiStoryTowers() {
    return numberofMultiStoryTowers;
  }

  /**
   * @param numberofMultiStoryTowers numberofMultiStoryTowers or {@code null} for none
   */
  public Project setNumberofMultiStoryTowers(java.lang.Integer numberofMultiStoryTowers) {
    this.numberofMultiStoryTowers = numberofMultiStoryTowers;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOffer() {
    return offer;
  }

  /**
   * @param offer offer or {@code null} for none
   */
  public Project setOffer(java.lang.String offer) {
    this.offer = offer;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getOfferAvailable() {
    return offerAvailable;
  }

  /**
   * @param offerAvailable offerAvailable or {@code null} for none
   */
  public Project setOfferAvailable(java.lang.Boolean offerAvailable) {
    this.offerAvailable = offerAvailable;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOfferLink() {
    return offerLink;
  }

  /**
   * @param offerLink offerLink or {@code null} for none
   */
  public Project setOfferLink(java.lang.String offerLink) {
    this.offerLink = offerLink;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getOnBoardingDate() {
    return onBoardingDate;
  }

  /**
   * @param onBoardingDate onBoardingDate or {@code null} for none
   */
  public Project setOnBoardingDate(java.lang.Long onBoardingDate) {
    this.onBoardingDate = onBoardingDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Image> getOtherImages() {
    return otherImages;
  }

  /**
   * @param otherImages otherImages or {@code null} for none
   */
  public Project setOtherImages(java.util.List<Image> otherImages) {
    this.otherImages = otherImages;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<PaymentPlan> getPaymentPlanList() {
    return paymentPlanList;
  }

  /**
   * @param paymentPlanList paymentPlanList or {@code null} for none
   */
  public Project setPaymentPlanList(java.util.List<PaymentPlan> paymentPlanList) {
    this.paymentPlanList = paymentPlanList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPhone() {
    return phone;
  }

  /**
   * @param phone phone or {@code null} for none
   */
  public Project setPhone(java.lang.String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPinCode() {
    return pinCode;
  }

  /**
   * @param pinCode pinCode or {@code null} for none
   */
  public Project setPinCode(java.lang.String pinCode) {
    this.pinCode = pinCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<KeyValuePair> getPlcDescriptionList() {
    return plcDescriptionList;
  }

  /**
   * @param plcDescriptionList plcDescriptionList or {@code null} for none
   */
  public Project setPlcDescriptionList(java.util.List<KeyValuePair> plcDescriptionList) {
    this.plcDescriptionList = plcDescriptionList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getPlcList() {
    return plcList;
  }

  /**
   * @param plcList plcList or {@code null} for none
   */
  public Project setPlcList(java.util.List<java.lang.String> plcList) {
    this.plcList = plcList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPossessionDate() {
    return possessionDate;
  }

  /**
   * @param possessionDate possessionDate or {@code null} for none
   */
  public Project setPossessionDate(java.lang.Long possessionDate) {
    this.possessionDate = possessionDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPreLaunchDate() {
    return preLaunchDate;
  }

  /**
   * @param preLaunchDate preLaunchDate or {@code null} for none
   */
  public Project setPreLaunchDate(java.lang.Long preLaunchDate) {
    this.preLaunchDate = preLaunchDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPriceRange() {
    return priceRange;
  }

  /**
   * @param priceRange priceRange or {@code null} for none
   */
  public Project setPriceRange(java.lang.String priceRange) {
    this.priceRange = priceRange;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<PriceTrend> getPriceTrends() {
    return priceTrends;
  }

  /**
   * @param priceTrends priceTrends or {@code null} for none
   */
  public Project setPriceTrends(java.util.List<PriceTrend> priceTrends) {
    this.priceTrends = priceTrends;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProjectArchitect() {
    return projectArchitect;
  }

  /**
   * @param projectArchitect projectArchitect or {@code null} for none
   */
  public Project setProjectArchitect(java.lang.String projectArchitect) {
    this.projectArchitect = projectArchitect;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProjectStatus() {
    return projectStatus;
  }

  /**
   * @param projectStatus projectStatus or {@code null} for none
   */
  public Project setProjectStatus(java.lang.String projectStatus) {
    this.projectStatus = projectStatus;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProjectSummary() {
    return projectSummary;
  }

  /**
   * @param projectSummary projectSummary or {@code null} for none
   */
  public Project setProjectSummary(java.lang.String projectSummary) {
    this.projectSummary = projectSummary;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProjectType() {
    return projectType;
  }

  /**
   * @param projectType projectType or {@code null} for none
   */
  public Project setProjectType(java.lang.String projectType) {
    this.projectType = projectType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProjectbrowcherPdfURL() {
    return projectbrowcherPdfURL;
  }

  /**
   * @param projectbrowcherPdfURL projectbrowcherPdfURL or {@code null} for none
   */
  public Project setProjectbrowcherPdfURL(java.lang.String projectbrowcherPdfURL) {
    this.projectbrowcherPdfURL = projectbrowcherPdfURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPropertyTypeJson() {
    return propertyTypeJson;
  }

  /**
   * @param propertyTypeJson propertyTypeJson or {@code null} for none
   */
  public Project setPropertyTypeJson(java.lang.String propertyTypeJson) {
    this.propertyTypeJson = propertyTypeJson;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Long> getPropertyTypeList() {
    return propertyTypeList;
  }

  /**
   * @param propertyTypeList propertyTypeList or {@code null} for none
   */
  public Project setPropertyTypeList(java.util.List<java.lang.Long> propertyTypeList) {
    this.propertyTypeList = propertyTypeList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPropertyTypeRange() {
    return propertyTypeRange;
  }

  /**
   * @param propertyTypeRange propertyTypeRange or {@code null} for none
   */
  public Project setPropertyTypeRange(java.lang.String propertyTypeRange) {
    this.propertyTypeRange = propertyTypeRange;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getReraId() {
    return reraId;
  }

  /**
   * @param reraId reraId or {@code null} for none
   */
  public Project setReraId(java.lang.String reraId) {
    this.reraId = reraId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getRmagentId() {
    return rmagentId;
  }

  /**
   * @param rmagentId rmagentId or {@code null} for none
   */
  public Project setRmagentId(java.lang.Long rmagentId) {
    this.rmagentId = rmagentId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRmagentName() {
    return rmagentName;
  }

  /**
   * @param rmagentName rmagentName or {@code null} for none
   */
  public Project setRmagentName(java.lang.String rmagentName) {
    this.rmagentName = rmagentName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRmagentPhone() {
    return rmagentPhone;
  }

  /**
   * @param rmagentPhone rmagentPhone or {@code null} for none
   */
  public Project setRmagentPhone(java.lang.String rmagentPhone) {
    this.rmagentPhone = rmagentPhone;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSCoverImage() {
    return sCoverImage;
  }

  /**
   * @param sCoverImage sCoverImage or {@code null} for none
   */
  public Project setSCoverImage(java.lang.String sCoverImage) {
    this.sCoverImage = sCoverImage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getSafetyScore() {
    return safetyScore;
  }

  /**
   * @param safetyScore safetyScore or {@code null} for none
   */
  public Project setSafetyScore(java.lang.Float safetyScore) {
    this.safetyScore = safetyScore;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSceoURL() {
    return sceoURL;
  }

  /**
   * @param sceoURL sceoURL or {@code null} for none
   */
  public Project setSceoURL(java.lang.String sceoURL) {
    this.sceoURL = sceoURL;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSearchNameInUp() {
    return searchNameInUp;
  }

  /**
   * @param searchNameInUp searchNameInUp or {@code null} for none
   */
  public Project setSearchNameInUp(java.lang.String searchNameInUp) {
    this.searchNameInUp = searchNameInUp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public FloorPlan getSitePlan() {
    return sitePlan;
  }

  /**
   * @param sitePlan sitePlan or {@code null} for none
   */
  public Project setSitePlan(FloorPlan sitePlan) {
    this.sitePlan = sitePlan;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSizeRange() {
    return sizeRange;
  }

  /**
   * @param sizeRange sizeRange or {@code null} for none
   */
  public Project setSizeRange(java.lang.String sizeRange) {
    this.sizeRange = sizeRange;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStartDate() {
    return startDate;
  }

  /**
   * @param startDate startDate or {@code null} for none
   */
  public Project setStartDate(java.lang.Long startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStartOfferDate() {
    return startOfferDate;
  }

  /**
   * @param startOfferDate startOfferDate or {@code null} for none
   */
  public Project setStartOfferDate(java.lang.Long startOfferDate) {
    this.startOfferDate = startOfferDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getState() {
    return state;
  }

  /**
   * @param state state or {@code null} for none
   */
  public Project setState(java.lang.String state) {
    this.state = state;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTargetAmount() {
    return targetAmount;
  }

  /**
   * @param targetAmount targetAmount or {@code null} for none
   */
  public Project setTargetAmount(java.lang.Long targetAmount) {
    this.targetAmount = targetAmount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getTentative() {
    return tentative;
  }

  /**
   * @param tentative tentative or {@code null} for none
   */
  public Project setTentative(java.lang.Boolean tentative) {
    this.tentative = tentative;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getTotalArea() {
    return totalArea;
  }

  /**
   * @param totalArea totalArea or {@code null} for none
   */
  public Project setTotalArea(java.lang.Float totalArea) {
    this.totalArea = totalArea;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTotalNumberBlock() {
    return totalNumberBlock;
  }

  /**
   * @param totalNumberBlock totalNumberBlock or {@code null} for none
   */
  public Project setTotalNumberBlock(java.lang.Integer totalNumberBlock) {
    this.totalNumberBlock = totalNumberBlock;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getValueForMoneyScore() {
    return valueForMoneyScore;
  }

  /**
   * @param valueForMoneyScore valueForMoneyScore or {@code null} for none
   */
  public Project setValueForMoneyScore(java.lang.Float valueForMoneyScore) {
    this.valueForMoneyScore = valueForMoneyScore;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Video> getVideos() {
    return videos;
  }

  /**
   * @param videos videos or {@code null} for none
   */
  public Project setVideos(java.util.List<Video> videos) {
    this.videos = videos;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getWalkThroughVideoURL() {
    return walkThroughVideoURL;
  }

  /**
   * @param walkThroughVideoURL walkThroughVideoURL or {@code null} for none
   */
  public Project setWalkThroughVideoURL(java.lang.String walkThroughVideoURL) {
    this.walkThroughVideoURL = walkThroughVideoURL;
    return this;
  }

  @Override
  public Project set(String fieldName, Object value) {
    return (Project) super.set(fieldName, value);
  }

  @Override
  public Project clone() {
    return (Project) super.clone();
  }

}
