/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2020-02-28 at 09:14:15 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.estimateEndPoint;

/**
 * Service definition for EstimateEndPoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link EstimateEndPointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class EstimateEndPoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.25.0 of the estimateEndPoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://redbrics-prod-backend.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "estimateEndPoint/v1/";

  /**
   * The default encoded batch path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.23
   */
  public static final String DEFAULT_BATCH_PATH = "batch";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public EstimateEndPoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  EstimateEndPoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "addEstimateProject99".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link AddEstimateProject99#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.buy.housing.backend.estimateEndPoint.model.EstimateProject}
   * @return the request
   */
  public AddEstimateProject99 addEstimateProject99(com.buy.housing.backend.estimateEndPoint.model.EstimateProject content) throws java.io.IOException {
    AddEstimateProject99 result = new AddEstimateProject99(content);
    initialize(result);
    return result;
  }

  public class AddEstimateProject99 extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.AddEstimateResponse> {

    private static final String REST_PATH = "addEstimateProject99";

    /**
     * Create a request for the method "addEstimateProject99".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link AddEstimateProject99#execute()} method to invoke the
     * remote operation. <p> {@link AddEstimateProject99#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link com.buy.housing.backend.estimateEndPoint.model.EstimateProject}
     * @since 1.13
     */
    protected AddEstimateProject99(com.buy.housing.backend.estimateEndPoint.model.EstimateProject content) {
      super(EstimateEndPoint.this, "POST", REST_PATH, content, com.buy.housing.backend.estimateEndPoint.model.AddEstimateResponse.class);
    }

    @Override
    public AddEstimateProject99 setAlt(java.lang.String alt) {
      return (AddEstimateProject99) super.setAlt(alt);
    }

    @Override
    public AddEstimateProject99 setFields(java.lang.String fields) {
      return (AddEstimateProject99) super.setFields(fields);
    }

    @Override
    public AddEstimateProject99 setKey(java.lang.String key) {
      return (AddEstimateProject99) super.setKey(key);
    }

    @Override
    public AddEstimateProject99 setOauthToken(java.lang.String oauthToken) {
      return (AddEstimateProject99) super.setOauthToken(oauthToken);
    }

    @Override
    public AddEstimateProject99 setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddEstimateProject99) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddEstimateProject99 setQuotaUser(java.lang.String quotaUser) {
      return (AddEstimateProject99) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddEstimateProject99 setUserIp(java.lang.String userIp) {
      return (AddEstimateProject99) super.setUserIp(userIp);
    }

    @Override
    public AddEstimateProject99 set(String parameterName, Object value) {
      return (AddEstimateProject99) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "addEstimateProjectList99".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link AddEstimateProjectList99#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.buy.housing.backend.estimateEndPoint.model.EstimateListRequest}
   * @return the request
   */
  public AddEstimateProjectList99 addEstimateProjectList99(com.buy.housing.backend.estimateEndPoint.model.EstimateListRequest content) throws java.io.IOException {
    AddEstimateProjectList99 result = new AddEstimateProjectList99(content);
    initialize(result);
    return result;
  }

  public class AddEstimateProjectList99 extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.AddEstimateResponse> {

    private static final String REST_PATH = "addEstimateProjectList99";

    /**
     * Create a request for the method "addEstimateProjectList99".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link AddEstimateProjectList99#execute()} method to invoke the
     * remote operation. <p> {@link AddEstimateProjectList99#initialize(com.google.api.client.googleap
     * is.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.buy.housing.backend.estimateEndPoint.model.EstimateListRequest}
     * @since 1.13
     */
    protected AddEstimateProjectList99(com.buy.housing.backend.estimateEndPoint.model.EstimateListRequest content) {
      super(EstimateEndPoint.this, "POST", REST_PATH, content, com.buy.housing.backend.estimateEndPoint.model.AddEstimateResponse.class);
    }

    @Override
    public AddEstimateProjectList99 setAlt(java.lang.String alt) {
      return (AddEstimateProjectList99) super.setAlt(alt);
    }

    @Override
    public AddEstimateProjectList99 setFields(java.lang.String fields) {
      return (AddEstimateProjectList99) super.setFields(fields);
    }

    @Override
    public AddEstimateProjectList99 setKey(java.lang.String key) {
      return (AddEstimateProjectList99) super.setKey(key);
    }

    @Override
    public AddEstimateProjectList99 setOauthToken(java.lang.String oauthToken) {
      return (AddEstimateProjectList99) super.setOauthToken(oauthToken);
    }

    @Override
    public AddEstimateProjectList99 setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddEstimateProjectList99) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddEstimateProjectList99 setQuotaUser(java.lang.String quotaUser) {
      return (AddEstimateProjectList99) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddEstimateProjectList99 setUserIp(java.lang.String userIp) {
      return (AddEstimateProjectList99) super.setUserIp(userIp);
    }

    @Override
    public AddEstimateProjectList99 set(String parameterName, Object value) {
      return (AddEstimateProjectList99) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "calculateEstimation".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link CalculateEstimation#execute()} method to invoke the remote
   * operation.
   *
   * @param latitude
   * @param longitude
   * @param size
   * @param type
   * @return the request
   */
  public CalculateEstimation calculateEstimation(java.lang.Double latitude, java.lang.Double longitude, java.lang.Float size, java.lang.String type) throws java.io.IOException {
    CalculateEstimation result = new CalculateEstimation(latitude, longitude, size, type);
    initialize(result);
    return result;
  }

  public class CalculateEstimation extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.CalculateEstimateResponse> {

    private static final String REST_PATH = "calculateEstimation/{latitude}/{longitude}/{size}/{type}";

    /**
     * Create a request for the method "calculateEstimation".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link CalculateEstimation#execute()} method to invoke the remote
     * operation. <p> {@link CalculateEstimation#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param latitude
     * @param longitude
     * @param size
     * @param type
     * @since 1.13
     */
    protected CalculateEstimation(java.lang.Double latitude, java.lang.Double longitude, java.lang.Float size, java.lang.String type) {
      super(EstimateEndPoint.this, "POST", REST_PATH, null, com.buy.housing.backend.estimateEndPoint.model.CalculateEstimateResponse.class);
      this.latitude = com.google.api.client.util.Preconditions.checkNotNull(latitude, "Required parameter latitude must be specified.");
      this.longitude = com.google.api.client.util.Preconditions.checkNotNull(longitude, "Required parameter longitude must be specified.");
      this.size = com.google.api.client.util.Preconditions.checkNotNull(size, "Required parameter size must be specified.");
      this.type = com.google.api.client.util.Preconditions.checkNotNull(type, "Required parameter type must be specified.");
    }

    @Override
    public CalculateEstimation setAlt(java.lang.String alt) {
      return (CalculateEstimation) super.setAlt(alt);
    }

    @Override
    public CalculateEstimation setFields(java.lang.String fields) {
      return (CalculateEstimation) super.setFields(fields);
    }

    @Override
    public CalculateEstimation setKey(java.lang.String key) {
      return (CalculateEstimation) super.setKey(key);
    }

    @Override
    public CalculateEstimation setOauthToken(java.lang.String oauthToken) {
      return (CalculateEstimation) super.setOauthToken(oauthToken);
    }

    @Override
    public CalculateEstimation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (CalculateEstimation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public CalculateEstimation setQuotaUser(java.lang.String quotaUser) {
      return (CalculateEstimation) super.setQuotaUser(quotaUser);
    }

    @Override
    public CalculateEstimation setUserIp(java.lang.String userIp) {
      return (CalculateEstimation) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Double latitude;

    /**

     */
    public java.lang.Double getLatitude() {
      return latitude;
    }

    public CalculateEstimation setLatitude(java.lang.Double latitude) {
      this.latitude = latitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double longitude;

    /**

     */
    public java.lang.Double getLongitude() {
      return longitude;
    }

    public CalculateEstimation setLongitude(java.lang.Double longitude) {
      this.longitude = longitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Float size;

    /**

     */
    public java.lang.Float getSize() {
      return size;
    }

    public CalculateEstimation setSize(java.lang.Float size) {
      this.size = size;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String type;

    /**

     */
    public java.lang.String getType() {
      return type;
    }

    public CalculateEstimation setType(java.lang.String type) {
      this.type = type;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String address;

    /**

     */
    public java.lang.String getAddress() {
      return address;
    }

    public CalculateEstimation setAddress(java.lang.String address) {
      this.address = address;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer bed;

    /**

     */
    public java.lang.Integer getBed() {
      return bed;
    }

    public CalculateEstimation setBed(java.lang.Integer bed) {
      this.bed = bed;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer age;

    /**

     */
    public java.lang.Integer getAge() {
      return age;
    }

    public CalculateEstimation setAge(java.lang.Integer age) {
      this.age = age;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer floor;

    /**

     */
    public java.lang.Integer getFloor() {
      return floor;
    }

    public CalculateEstimation setFloor(java.lang.Integer floor) {
      this.floor = floor;
      return this;
    }

    @Override
    public CalculateEstimation set(String parameterName, Object value) {
      return (CalculateEstimation) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "clicworthNotifyPriceChange".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link ClicworthNotifyPriceChange#execute()} method to invoke the
   * remote operation.
   *
   * @param otp
   * @param userId
   * @param latitude
   * @param longitude
   * @param size
   * @param type
   * @return the request
   */
  public ClicworthNotifyPriceChange clicworthNotifyPriceChange(java.lang.String otp, java.lang.Long userId, java.lang.Double latitude, java.lang.Double longitude, java.lang.Float size, java.lang.String type) throws java.io.IOException {
    ClicworthNotifyPriceChange result = new ClicworthNotifyPriceChange(otp, userId, latitude, longitude, size, type);
    initialize(result);
    return result;
  }

  public class ClicworthNotifyPriceChange extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "clicworthNotifyPriceChange/{otp}/{userId}/{latitude}/{longitude}/{size}/{type}";

    /**
     * Create a request for the method "clicworthNotifyPriceChange".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link ClicworthNotifyPriceChange#execute()} method to invoke the
     * remote operation. <p> {@link ClicworthNotifyPriceChange#initialize(com.google.api.client.google
     * apis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param otp
     * @param userId
     * @param latitude
     * @param longitude
     * @param size
     * @param type
     * @since 1.13
     */
    protected ClicworthNotifyPriceChange(java.lang.String otp, java.lang.Long userId, java.lang.Double latitude, java.lang.Double longitude, java.lang.Float size, java.lang.String type) {
      super(EstimateEndPoint.this, "POST", REST_PATH, null, com.buy.housing.backend.estimateEndPoint.model.CommonResponse.class);
      this.otp = com.google.api.client.util.Preconditions.checkNotNull(otp, "Required parameter otp must be specified.");
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
      this.latitude = com.google.api.client.util.Preconditions.checkNotNull(latitude, "Required parameter latitude must be specified.");
      this.longitude = com.google.api.client.util.Preconditions.checkNotNull(longitude, "Required parameter longitude must be specified.");
      this.size = com.google.api.client.util.Preconditions.checkNotNull(size, "Required parameter size must be specified.");
      this.type = com.google.api.client.util.Preconditions.checkNotNull(type, "Required parameter type must be specified.");
    }

    @Override
    public ClicworthNotifyPriceChange setAlt(java.lang.String alt) {
      return (ClicworthNotifyPriceChange) super.setAlt(alt);
    }

    @Override
    public ClicworthNotifyPriceChange setFields(java.lang.String fields) {
      return (ClicworthNotifyPriceChange) super.setFields(fields);
    }

    @Override
    public ClicworthNotifyPriceChange setKey(java.lang.String key) {
      return (ClicworthNotifyPriceChange) super.setKey(key);
    }

    @Override
    public ClicworthNotifyPriceChange setOauthToken(java.lang.String oauthToken) {
      return (ClicworthNotifyPriceChange) super.setOauthToken(oauthToken);
    }

    @Override
    public ClicworthNotifyPriceChange setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ClicworthNotifyPriceChange) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ClicworthNotifyPriceChange setQuotaUser(java.lang.String quotaUser) {
      return (ClicworthNotifyPriceChange) super.setQuotaUser(quotaUser);
    }

    @Override
    public ClicworthNotifyPriceChange setUserIp(java.lang.String userIp) {
      return (ClicworthNotifyPriceChange) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String otp;

    /**

     */
    public java.lang.String getOtp() {
      return otp;
    }

    public ClicworthNotifyPriceChange setOtp(java.lang.String otp) {
      this.otp = otp;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long userId;

    /**

     */
    public java.lang.Long getUserId() {
      return userId;
    }

    public ClicworthNotifyPriceChange setUserId(java.lang.Long userId) {
      this.userId = userId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double latitude;

    /**

     */
    public java.lang.Double getLatitude() {
      return latitude;
    }

    public ClicworthNotifyPriceChange setLatitude(java.lang.Double latitude) {
      this.latitude = latitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double longitude;

    /**

     */
    public java.lang.Double getLongitude() {
      return longitude;
    }

    public ClicworthNotifyPriceChange setLongitude(java.lang.Double longitude) {
      this.longitude = longitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Float size;

    /**

     */
    public java.lang.Float getSize() {
      return size;
    }

    public ClicworthNotifyPriceChange setSize(java.lang.Float size) {
      this.size = size;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String type;

    /**

     */
    public java.lang.String getType() {
      return type;
    }

    public ClicworthNotifyPriceChange setType(java.lang.String type) {
      this.type = type;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String address;

    /**

     */
    public java.lang.String getAddress() {
      return address;
    }

    public ClicworthNotifyPriceChange setAddress(java.lang.String address) {
      this.address = address;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer bed;

    /**

     */
    public java.lang.Integer getBed() {
      return bed;
    }

    public ClicworthNotifyPriceChange setBed(java.lang.Integer bed) {
      this.bed = bed;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer age;

    /**

     */
    public java.lang.Integer getAge() {
      return age;
    }

    public ClicworthNotifyPriceChange setAge(java.lang.Integer age) {
      this.age = age;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer floor;

    /**

     */
    public java.lang.Integer getFloor() {
      return floor;
    }

    public ClicworthNotifyPriceChange setFloor(java.lang.Integer floor) {
      this.floor = floor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Float price;

    /**

     */
    public java.lang.Float getPrice() {
      return price;
    }

    public ClicworthNotifyPriceChange setPrice(java.lang.Float price) {
      this.price = price;
      return this;
    }

    @Override
    public ClicworthNotifyPriceChange set(String parameterName, Object value) {
      return (ClicworthNotifyPriceChange) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "deleteEstimate".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link DeleteEstimate#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.buy.housing.backend.estimateEndPoint.model.DeleteEstimateListRequest}
   * @return the request
   */
  public DeleteEstimate deleteEstimate(com.buy.housing.backend.estimateEndPoint.model.DeleteEstimateListRequest content) throws java.io.IOException {
    DeleteEstimate result = new DeleteEstimate(content);
    initialize(result);
    return result;
  }

  public class DeleteEstimate extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.AddEstimateResponse> {

    private static final String REST_PATH = "estimate";

    /**
     * Create a request for the method "deleteEstimate".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link DeleteEstimate#execute()} method to invoke the remote
     * operation. <p> {@link DeleteEstimate#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.buy.housing.backend.estimateEndPoint.model.DeleteEstimateListRequest}
     * @since 1.13
     */
    protected DeleteEstimate(com.buy.housing.backend.estimateEndPoint.model.DeleteEstimateListRequest content) {
      super(EstimateEndPoint.this, "POST", REST_PATH, content, com.buy.housing.backend.estimateEndPoint.model.AddEstimateResponse.class);
    }

    @Override
    public DeleteEstimate setAlt(java.lang.String alt) {
      return (DeleteEstimate) super.setAlt(alt);
    }

    @Override
    public DeleteEstimate setFields(java.lang.String fields) {
      return (DeleteEstimate) super.setFields(fields);
    }

    @Override
    public DeleteEstimate setKey(java.lang.String key) {
      return (DeleteEstimate) super.setKey(key);
    }

    @Override
    public DeleteEstimate setOauthToken(java.lang.String oauthToken) {
      return (DeleteEstimate) super.setOauthToken(oauthToken);
    }

    @Override
    public DeleteEstimate setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (DeleteEstimate) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public DeleteEstimate setQuotaUser(java.lang.String quotaUser) {
      return (DeleteEstimate) super.setQuotaUser(quotaUser);
    }

    @Override
    public DeleteEstimate setUserIp(java.lang.String userIp) {
      return (DeleteEstimate) super.setUserIp(userIp);
    }

    @Override
    public DeleteEstimate set(String parameterName, Object value) {
      return (DeleteEstimate) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "estimationFeedback".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link EstimationFeedback#execute()} method to invoke the remote
   * operation.
   *
   * @param latitude
   * @param longitude
   * @param size
   * @param type
   * @param feedback
   * @return the request
   */
  public EstimationFeedback estimationFeedback(java.lang.Double latitude, java.lang.Double longitude, java.lang.Float size, java.lang.String type, java.lang.String feedback) throws java.io.IOException {
    EstimationFeedback result = new EstimationFeedback(latitude, longitude, size, type, feedback);
    initialize(result);
    return result;
  }

  public class EstimationFeedback extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "estimationFeedback/{latitude}/{longitude}/{size}/{type}/{feedback}";

    /**
     * Create a request for the method "estimationFeedback".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link EstimationFeedback#execute()} method to invoke the remote
     * operation. <p> {@link EstimationFeedback#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param latitude
     * @param longitude
     * @param size
     * @param type
     * @param feedback
     * @since 1.13
     */
    protected EstimationFeedback(java.lang.Double latitude, java.lang.Double longitude, java.lang.Float size, java.lang.String type, java.lang.String feedback) {
      super(EstimateEndPoint.this, "POST", REST_PATH, null, com.buy.housing.backend.estimateEndPoint.model.CommonResponse.class);
      this.latitude = com.google.api.client.util.Preconditions.checkNotNull(latitude, "Required parameter latitude must be specified.");
      this.longitude = com.google.api.client.util.Preconditions.checkNotNull(longitude, "Required parameter longitude must be specified.");
      this.size = com.google.api.client.util.Preconditions.checkNotNull(size, "Required parameter size must be specified.");
      this.type = com.google.api.client.util.Preconditions.checkNotNull(type, "Required parameter type must be specified.");
      this.feedback = com.google.api.client.util.Preconditions.checkNotNull(feedback, "Required parameter feedback must be specified.");
    }

    @Override
    public EstimationFeedback setAlt(java.lang.String alt) {
      return (EstimationFeedback) super.setAlt(alt);
    }

    @Override
    public EstimationFeedback setFields(java.lang.String fields) {
      return (EstimationFeedback) super.setFields(fields);
    }

    @Override
    public EstimationFeedback setKey(java.lang.String key) {
      return (EstimationFeedback) super.setKey(key);
    }

    @Override
    public EstimationFeedback setOauthToken(java.lang.String oauthToken) {
      return (EstimationFeedback) super.setOauthToken(oauthToken);
    }

    @Override
    public EstimationFeedback setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (EstimationFeedback) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public EstimationFeedback setQuotaUser(java.lang.String quotaUser) {
      return (EstimationFeedback) super.setQuotaUser(quotaUser);
    }

    @Override
    public EstimationFeedback setUserIp(java.lang.String userIp) {
      return (EstimationFeedback) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Double latitude;

    /**

     */
    public java.lang.Double getLatitude() {
      return latitude;
    }

    public EstimationFeedback setLatitude(java.lang.Double latitude) {
      this.latitude = latitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double longitude;

    /**

     */
    public java.lang.Double getLongitude() {
      return longitude;
    }

    public EstimationFeedback setLongitude(java.lang.Double longitude) {
      this.longitude = longitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Float size;

    /**

     */
    public java.lang.Float getSize() {
      return size;
    }

    public EstimationFeedback setSize(java.lang.Float size) {
      this.size = size;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String type;

    /**

     */
    public java.lang.String getType() {
      return type;
    }

    public EstimationFeedback setType(java.lang.String type) {
      this.type = type;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String feedback;

    /**

     */
    public java.lang.String getFeedback() {
      return feedback;
    }

    public EstimationFeedback setFeedback(java.lang.String feedback) {
      this.feedback = feedback;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String address;

    /**

     */
    public java.lang.String getAddress() {
      return address;
    }

    public EstimationFeedback setAddress(java.lang.String address) {
      this.address = address;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer bed;

    /**

     */
    public java.lang.Integer getBed() {
      return bed;
    }

    public EstimationFeedback setBed(java.lang.Integer bed) {
      this.bed = bed;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer age;

    /**

     */
    public java.lang.Integer getAge() {
      return age;
    }

    public EstimationFeedback setAge(java.lang.Integer age) {
      this.age = age;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer floor;

    /**

     */
    public java.lang.Integer getFloor() {
      return floor;
    }

    public EstimationFeedback setFloor(java.lang.Integer floor) {
      this.floor = floor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double bsp;

    /**

     */
    public java.lang.Double getBsp() {
      return bsp;
    }

    public EstimationFeedback setBsp(java.lang.Double bsp) {
      this.bsp = bsp;
      return this;
    }

    @Override
    public EstimationFeedback set(String parameterName, Object value) {
      return (EstimationFeedback) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getEstimate".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link GetEstimate#execute()} method to invoke the remote
   * operation.
   *
   * @param offset
   * @param limit
   * @return the request
   */
  public GetEstimate getEstimate(java.lang.Integer offset, java.lang.Integer limit) throws java.io.IOException {
    GetEstimate result = new GetEstimate(offset, limit);
    initialize(result);
    return result;
  }

  public class GetEstimate extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.EstimateResponse> {

    private static final String REST_PATH = "estimateresponse/{offset}/{limit}";

    /**
     * Create a request for the method "getEstimate".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link GetEstimate#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetEstimate#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param offset
     * @param limit
     * @since 1.13
     */
    protected GetEstimate(java.lang.Integer offset, java.lang.Integer limit) {
      super(EstimateEndPoint.this, "GET", REST_PATH, null, com.buy.housing.backend.estimateEndPoint.model.EstimateResponse.class);
      this.offset = com.google.api.client.util.Preconditions.checkNotNull(offset, "Required parameter offset must be specified.");
      this.limit = com.google.api.client.util.Preconditions.checkNotNull(limit, "Required parameter limit must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetEstimate setAlt(java.lang.String alt) {
      return (GetEstimate) super.setAlt(alt);
    }

    @Override
    public GetEstimate setFields(java.lang.String fields) {
      return (GetEstimate) super.setFields(fields);
    }

    @Override
    public GetEstimate setKey(java.lang.String key) {
      return (GetEstimate) super.setKey(key);
    }

    @Override
    public GetEstimate setOauthToken(java.lang.String oauthToken) {
      return (GetEstimate) super.setOauthToken(oauthToken);
    }

    @Override
    public GetEstimate setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetEstimate) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetEstimate setQuotaUser(java.lang.String quotaUser) {
      return (GetEstimate) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetEstimate setUserIp(java.lang.String userIp) {
      return (GetEstimate) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Integer offset;

    /**

     */
    public java.lang.Integer getOffset() {
      return offset;
    }

    public GetEstimate setOffset(java.lang.Integer offset) {
      this.offset = offset;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public GetEstimate setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long cityId;

    /**

     */
    public java.lang.Long getCityId() {
      return cityId;
    }

    public GetEstimate setCityId(java.lang.Long cityId) {
      this.cityId = cityId;
      return this;
    }

    @Override
    public GetEstimate set(String parameterName, Object value) {
      return (GetEstimate) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getEstimateCityList".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link GetEstimateCityList#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public GetEstimateCityList getEstimateCityList() throws java.io.IOException {
    GetEstimateCityList result = new GetEstimateCityList();
    initialize(result);
    return result;
  }

  public class GetEstimateCityList extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.CityCollection> {

    private static final String REST_PATH = "citycollection";

    /**
     * Create a request for the method "getEstimateCityList".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link GetEstimateCityList#execute()} method to invoke the remote
     * operation. <p> {@link GetEstimateCityList#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetEstimateCityList() {
      super(EstimateEndPoint.this, "GET", REST_PATH, null, com.buy.housing.backend.estimateEndPoint.model.CityCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetEstimateCityList setAlt(java.lang.String alt) {
      return (GetEstimateCityList) super.setAlt(alt);
    }

    @Override
    public GetEstimateCityList setFields(java.lang.String fields) {
      return (GetEstimateCityList) super.setFields(fields);
    }

    @Override
    public GetEstimateCityList setKey(java.lang.String key) {
      return (GetEstimateCityList) super.setKey(key);
    }

    @Override
    public GetEstimateCityList setOauthToken(java.lang.String oauthToken) {
      return (GetEstimateCityList) super.setOauthToken(oauthToken);
    }

    @Override
    public GetEstimateCityList setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetEstimateCityList) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetEstimateCityList setQuotaUser(java.lang.String quotaUser) {
      return (GetEstimateCityList) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetEstimateCityList setUserIp(java.lang.String userIp) {
      return (GetEstimateCityList) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean live;

    /**

     */
    public java.lang.Boolean getLive() {
      return live;
    }

    public GetEstimateCityList setLive(java.lang.Boolean live) {
      this.live = live;
      return this;
    }

    @Override
    public GetEstimateCityList set(String parameterName, Object value) {
      return (GetEstimateCityList) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getEstimationResults".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link GetEstimationResults#execute()} method to invoke the remote
   * operation.
   *
   * @param agntId
   * @param token
   * @param offset
   * @param limit
   * @return the request
   */
  public GetEstimationResults getEstimationResults(java.lang.Long agntId, java.lang.String token, java.lang.Integer offset, java.lang.Integer limit) throws java.io.IOException {
    GetEstimationResults result = new GetEstimationResults(agntId, token, offset, limit);
    initialize(result);
    return result;
  }

  public class GetEstimationResults extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.EstimateResultsList> {

    private static final String REST_PATH = "estimateresultslist/{agntId}/{token}/{offset}/{limit}";

    /**
     * Create a request for the method "getEstimationResults".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link GetEstimationResults#execute()} method to invoke the
     * remote operation. <p> {@link GetEstimationResults#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param agntId
     * @param token
     * @param offset
     * @param limit
     * @since 1.13
     */
    protected GetEstimationResults(java.lang.Long agntId, java.lang.String token, java.lang.Integer offset, java.lang.Integer limit) {
      super(EstimateEndPoint.this, "GET", REST_PATH, null, com.buy.housing.backend.estimateEndPoint.model.EstimateResultsList.class);
      this.agntId = com.google.api.client.util.Preconditions.checkNotNull(agntId, "Required parameter agntId must be specified.");
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
      this.offset = com.google.api.client.util.Preconditions.checkNotNull(offset, "Required parameter offset must be specified.");
      this.limit = com.google.api.client.util.Preconditions.checkNotNull(limit, "Required parameter limit must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetEstimationResults setAlt(java.lang.String alt) {
      return (GetEstimationResults) super.setAlt(alt);
    }

    @Override
    public GetEstimationResults setFields(java.lang.String fields) {
      return (GetEstimationResults) super.setFields(fields);
    }

    @Override
    public GetEstimationResults setKey(java.lang.String key) {
      return (GetEstimationResults) super.setKey(key);
    }

    @Override
    public GetEstimationResults setOauthToken(java.lang.String oauthToken) {
      return (GetEstimationResults) super.setOauthToken(oauthToken);
    }

    @Override
    public GetEstimationResults setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetEstimationResults) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetEstimationResults setQuotaUser(java.lang.String quotaUser) {
      return (GetEstimationResults) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetEstimationResults setUserIp(java.lang.String userIp) {
      return (GetEstimationResults) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long agntId;

    /**

     */
    public java.lang.Long getAgntId() {
      return agntId;
    }

    public GetEstimationResults setAgntId(java.lang.Long agntId) {
      this.agntId = agntId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String token;

    /**

     */
    public java.lang.String getToken() {
      return token;
    }

    public GetEstimationResults setToken(java.lang.String token) {
      this.token = token;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer offset;

    /**

     */
    public java.lang.Integer getOffset() {
      return offset;
    }

    public GetEstimationResults setOffset(java.lang.Integer offset) {
      this.offset = offset;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public GetEstimationResults setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public GetEstimationResults set(String parameterName, Object value) {
      return (GetEstimationResults) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "notifyPriceChange".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link NotifyPriceChange#execute()} method to invoke the remote
   * operation.
   *
   * @param userId
   * @param latitude
   * @param longitude
   * @param size
   * @param type
   * @return the request
   */
  public NotifyPriceChange notifyPriceChange(java.lang.Long userId, java.lang.Double latitude, java.lang.Double longitude, java.lang.Float size, java.lang.String type) throws java.io.IOException {
    NotifyPriceChange result = new NotifyPriceChange(userId, latitude, longitude, size, type);
    initialize(result);
    return result;
  }

  public class NotifyPriceChange extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "notifyPriceChange/{userId}/{latitude}/{longitude}/{size}/{type}";

    /**
     * Create a request for the method "notifyPriceChange".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link NotifyPriceChange#execute()} method to invoke the remote
     * operation. <p> {@link NotifyPriceChange#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param userId
     * @param latitude
     * @param longitude
     * @param size
     * @param type
     * @since 1.13
     */
    protected NotifyPriceChange(java.lang.Long userId, java.lang.Double latitude, java.lang.Double longitude, java.lang.Float size, java.lang.String type) {
      super(EstimateEndPoint.this, "POST", REST_PATH, null, com.buy.housing.backend.estimateEndPoint.model.CommonResponse.class);
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
      this.latitude = com.google.api.client.util.Preconditions.checkNotNull(latitude, "Required parameter latitude must be specified.");
      this.longitude = com.google.api.client.util.Preconditions.checkNotNull(longitude, "Required parameter longitude must be specified.");
      this.size = com.google.api.client.util.Preconditions.checkNotNull(size, "Required parameter size must be specified.");
      this.type = com.google.api.client.util.Preconditions.checkNotNull(type, "Required parameter type must be specified.");
    }

    @Override
    public NotifyPriceChange setAlt(java.lang.String alt) {
      return (NotifyPriceChange) super.setAlt(alt);
    }

    @Override
    public NotifyPriceChange setFields(java.lang.String fields) {
      return (NotifyPriceChange) super.setFields(fields);
    }

    @Override
    public NotifyPriceChange setKey(java.lang.String key) {
      return (NotifyPriceChange) super.setKey(key);
    }

    @Override
    public NotifyPriceChange setOauthToken(java.lang.String oauthToken) {
      return (NotifyPriceChange) super.setOauthToken(oauthToken);
    }

    @Override
    public NotifyPriceChange setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (NotifyPriceChange) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public NotifyPriceChange setQuotaUser(java.lang.String quotaUser) {
      return (NotifyPriceChange) super.setQuotaUser(quotaUser);
    }

    @Override
    public NotifyPriceChange setUserIp(java.lang.String userIp) {
      return (NotifyPriceChange) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long userId;

    /**

     */
    public java.lang.Long getUserId() {
      return userId;
    }

    public NotifyPriceChange setUserId(java.lang.Long userId) {
      this.userId = userId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double latitude;

    /**

     */
    public java.lang.Double getLatitude() {
      return latitude;
    }

    public NotifyPriceChange setLatitude(java.lang.Double latitude) {
      this.latitude = latitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double longitude;

    /**

     */
    public java.lang.Double getLongitude() {
      return longitude;
    }

    public NotifyPriceChange setLongitude(java.lang.Double longitude) {
      this.longitude = longitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Float size;

    /**

     */
    public java.lang.Float getSize() {
      return size;
    }

    public NotifyPriceChange setSize(java.lang.Float size) {
      this.size = size;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String type;

    /**

     */
    public java.lang.String getType() {
      return type;
    }

    public NotifyPriceChange setType(java.lang.String type) {
      this.type = type;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String address;

    /**

     */
    public java.lang.String getAddress() {
      return address;
    }

    public NotifyPriceChange setAddress(java.lang.String address) {
      this.address = address;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer bed;

    /**

     */
    public java.lang.Integer getBed() {
      return bed;
    }

    public NotifyPriceChange setBed(java.lang.Integer bed) {
      this.bed = bed;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer age;

    /**

     */
    public java.lang.Integer getAge() {
      return age;
    }

    public NotifyPriceChange setAge(java.lang.Integer age) {
      this.age = age;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer floor;

    /**

     */
    public java.lang.Integer getFloor() {
      return floor;
    }

    public NotifyPriceChange setFloor(java.lang.Integer floor) {
      this.floor = floor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Float price;

    /**

     */
    public java.lang.Float getPrice() {
      return price;
    }

    public NotifyPriceChange setPrice(java.lang.Float price) {
      this.price = price;
      return this;
    }

    @Override
    public NotifyPriceChange set(String parameterName, Object value) {
      return (NotifyPriceChange) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "registerClicworthUser".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link RegisterClicworthUser#execute()} method to invoke the remote
   * operation.
   *
   * @param phone
   * @param name
   * @param email
   * @return the request
   */
  public RegisterClicworthUser registerClicworthUser(java.lang.String phone, java.lang.String name, java.lang.String email) throws java.io.IOException {
    RegisterClicworthUser result = new RegisterClicworthUser(phone, name, email);
    initialize(result);
    return result;
  }

  public class RegisterClicworthUser extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "registerClicworthUser/{phone}/{name}/{email}";

    /**
     * Create a request for the method "registerClicworthUser".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link RegisterClicworthUser#execute()} method to invoke the
     * remote operation. <p> {@link RegisterClicworthUser#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param phone
     * @param name
     * @param email
     * @since 1.13
     */
    protected RegisterClicworthUser(java.lang.String phone, java.lang.String name, java.lang.String email) {
      super(EstimateEndPoint.this, "GET", REST_PATH, null, com.buy.housing.backend.estimateEndPoint.model.CommonResponse.class);
      this.phone = com.google.api.client.util.Preconditions.checkNotNull(phone, "Required parameter phone must be specified.");
      this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public RegisterClicworthUser setAlt(java.lang.String alt) {
      return (RegisterClicworthUser) super.setAlt(alt);
    }

    @Override
    public RegisterClicworthUser setFields(java.lang.String fields) {
      return (RegisterClicworthUser) super.setFields(fields);
    }

    @Override
    public RegisterClicworthUser setKey(java.lang.String key) {
      return (RegisterClicworthUser) super.setKey(key);
    }

    @Override
    public RegisterClicworthUser setOauthToken(java.lang.String oauthToken) {
      return (RegisterClicworthUser) super.setOauthToken(oauthToken);
    }

    @Override
    public RegisterClicworthUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RegisterClicworthUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RegisterClicworthUser setQuotaUser(java.lang.String quotaUser) {
      return (RegisterClicworthUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public RegisterClicworthUser setUserIp(java.lang.String userIp) {
      return (RegisterClicworthUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String phone;

    /**

     */
    public java.lang.String getPhone() {
      return phone;
    }

    public RegisterClicworthUser setPhone(java.lang.String phone) {
      this.phone = phone;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String name;

    /**

     */
    public java.lang.String getName() {
      return name;
    }

    public RegisterClicworthUser setName(java.lang.String name) {
      this.name = name;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public RegisterClicworthUser setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double latitude;

    /**

     */
    public java.lang.Double getLatitude() {
      return latitude;
    }

    public RegisterClicworthUser setLatitude(java.lang.Double latitude) {
      this.latitude = latitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Double longitude;

    /**

     */
    public java.lang.Double getLongitude() {
      return longitude;
    }

    public RegisterClicworthUser setLongitude(java.lang.Double longitude) {
      this.longitude = longitude;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Float size;

    /**

     */
    public java.lang.Float getSize() {
      return size;
    }

    public RegisterClicworthUser setSize(java.lang.Float size) {
      this.size = size;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String type;

    /**

     */
    public java.lang.String getType() {
      return type;
    }

    public RegisterClicworthUser setType(java.lang.String type) {
      this.type = type;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String address;

    /**

     */
    public java.lang.String getAddress() {
      return address;
    }

    public RegisterClicworthUser setAddress(java.lang.String address) {
      this.address = address;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer bed;

    /**

     */
    public java.lang.Integer getBed() {
      return bed;
    }

    public RegisterClicworthUser setBed(java.lang.Integer bed) {
      this.bed = bed;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer age;

    /**

     */
    public java.lang.Integer getAge() {
      return age;
    }

    public RegisterClicworthUser setAge(java.lang.Integer age) {
      this.age = age;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer floor;

    /**

     */
    public java.lang.Integer getFloor() {
      return floor;
    }

    public RegisterClicworthUser setFloor(java.lang.Integer floor) {
      this.floor = floor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Float price;

    /**

     */
    public java.lang.Float getPrice() {
      return price;
    }

    public RegisterClicworthUser setPrice(java.lang.Float price) {
      this.price = price;
      return this;
    }

    @Override
    public RegisterClicworthUser set(String parameterName, Object value) {
      return (RegisterClicworthUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "reindexAllEstimation".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link ReindexAllEstimation#execute()} method to invoke the remote
   * operation.
   *
   * @param token
   * @param offset
   * @param limit
   * @param content the {@link com.buy.housing.backend.estimateEndPoint.model.EstimateListRequest}
   * @return the request
   */
  public ReindexAllEstimation reindexAllEstimation(java.lang.String token, java.lang.Integer offset, java.lang.Integer limit, com.buy.housing.backend.estimateEndPoint.model.EstimateListRequest content) throws java.io.IOException {
    ReindexAllEstimation result = new ReindexAllEstimation(token, offset, limit, content);
    initialize(result);
    return result;
  }

  public class ReindexAllEstimation extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "reindexAllEstimation/{token}/{offset}/{limit}";

    /**
     * Create a request for the method "reindexAllEstimation".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link ReindexAllEstimation#execute()} method to invoke the
     * remote operation. <p> {@link ReindexAllEstimation#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param token
     * @param offset
     * @param limit
     * @param content the {@link com.buy.housing.backend.estimateEndPoint.model.EstimateListRequest}
     * @since 1.13
     */
    protected ReindexAllEstimation(java.lang.String token, java.lang.Integer offset, java.lang.Integer limit, com.buy.housing.backend.estimateEndPoint.model.EstimateListRequest content) {
      super(EstimateEndPoint.this, "POST", REST_PATH, content, com.buy.housing.backend.estimateEndPoint.model.CommonResponse.class);
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
      this.offset = com.google.api.client.util.Preconditions.checkNotNull(offset, "Required parameter offset must be specified.");
      this.limit = com.google.api.client.util.Preconditions.checkNotNull(limit, "Required parameter limit must be specified.");
    }

    @Override
    public ReindexAllEstimation setAlt(java.lang.String alt) {
      return (ReindexAllEstimation) super.setAlt(alt);
    }

    @Override
    public ReindexAllEstimation setFields(java.lang.String fields) {
      return (ReindexAllEstimation) super.setFields(fields);
    }

    @Override
    public ReindexAllEstimation setKey(java.lang.String key) {
      return (ReindexAllEstimation) super.setKey(key);
    }

    @Override
    public ReindexAllEstimation setOauthToken(java.lang.String oauthToken) {
      return (ReindexAllEstimation) super.setOauthToken(oauthToken);
    }

    @Override
    public ReindexAllEstimation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ReindexAllEstimation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ReindexAllEstimation setQuotaUser(java.lang.String quotaUser) {
      return (ReindexAllEstimation) super.setQuotaUser(quotaUser);
    }

    @Override
    public ReindexAllEstimation setUserIp(java.lang.String userIp) {
      return (ReindexAllEstimation) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String token;

    /**

     */
    public java.lang.String getToken() {
      return token;
    }

    public ReindexAllEstimation setToken(java.lang.String token) {
      this.token = token;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer offset;

    /**

     */
    public java.lang.Integer getOffset() {
      return offset;
    }

    public ReindexAllEstimation setOffset(java.lang.Integer offset) {
      this.offset = offset;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ReindexAllEstimation setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ReindexAllEstimation set(String parameterName, Object value) {
      return (ReindexAllEstimation) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAllEstimationIndexes".
   *
   * This request holds the parameters needed by the estimateEndPoint server.  After setting any
   * optional parameters, call the {@link RemoveAllEstimationIndexes#execute()} method to invoke the
   * remote operation.
   *
   * @param token
   * @return the request
   */
  public RemoveAllEstimationIndexes removeAllEstimationIndexes(java.lang.String token) throws java.io.IOException {
    RemoveAllEstimationIndexes result = new RemoveAllEstimationIndexes(token);
    initialize(result);
    return result;
  }

  public class RemoveAllEstimationIndexes extends EstimateEndPointRequest<com.buy.housing.backend.estimateEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "allestimationindexes/{token}";

    /**
     * Create a request for the method "removeAllEstimationIndexes".
     *
     * This request holds the parameters needed by the the estimateEndPoint server.  After setting any
     * optional parameters, call the {@link RemoveAllEstimationIndexes#execute()} method to invoke the
     * remote operation. <p> {@link RemoveAllEstimationIndexes#initialize(com.google.api.client.google
     * apis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param token
     * @since 1.13
     */
    protected RemoveAllEstimationIndexes(java.lang.String token) {
      super(EstimateEndPoint.this, "GET", REST_PATH, null, com.buy.housing.backend.estimateEndPoint.model.CommonResponse.class);
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public RemoveAllEstimationIndexes setAlt(java.lang.String alt) {
      return (RemoveAllEstimationIndexes) super.setAlt(alt);
    }

    @Override
    public RemoveAllEstimationIndexes setFields(java.lang.String fields) {
      return (RemoveAllEstimationIndexes) super.setFields(fields);
    }

    @Override
    public RemoveAllEstimationIndexes setKey(java.lang.String key) {
      return (RemoveAllEstimationIndexes) super.setKey(key);
    }

    @Override
    public RemoveAllEstimationIndexes setOauthToken(java.lang.String oauthToken) {
      return (RemoveAllEstimationIndexes) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAllEstimationIndexes setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAllEstimationIndexes) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAllEstimationIndexes setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAllEstimationIndexes) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAllEstimationIndexes setUserIp(java.lang.String userIp) {
      return (RemoveAllEstimationIndexes) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String token;

    /**

     */
    public java.lang.String getToken() {
      return token;
    }

    public RemoveAllEstimationIndexes setToken(java.lang.String token) {
      this.token = token;
      return this;
    }

    @Override
    public RemoveAllEstimationIndexes set(String parameterName, Object value) {
      return (RemoveAllEstimationIndexes) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link EstimateEndPoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);

    }

    /** Builds a new instance of {@link EstimateEndPoint}. */
    @Override
    public EstimateEndPoint build() {
      return new EstimateEndPoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }



    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link EstimateEndPointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setEstimateEndPointRequestInitializer(
        EstimateEndPointRequestInitializer estimateendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(estimateendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
