/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2019-10-23 at 04:35:07 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.loanEndPoint;

/**
 * Service definition for LoanEndPoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link LoanEndPointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class LoanEndPoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.25.0 of the loanEndPoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://housingtestserver.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "loanEndPoint/v1/";

  /**
   * The default encoded batch path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.23
   */
  public static final String DEFAULT_BATCH_PATH = "batch";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public LoanEndPoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  LoanEndPoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "addLoanLeadDoc".
   *
   * This request holds the parameters needed by the loanEndPoint server.  After setting any optional
   * parameters, call the {@link AddLoanLeadDoc#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param token
   * @param loanId
   * @param content the {@link com.buy.housing.backend.loanEndPoint.model.Document}
   * @return the request
   */
  public AddLoanLeadDoc addLoanLeadDoc(java.lang.Long id, java.lang.String token, java.lang.Long loanId, com.buy.housing.backend.loanEndPoint.model.Document content) throws java.io.IOException {
    AddLoanLeadDoc result = new AddLoanLeadDoc(id, token, loanId, content);
    initialize(result);
    return result;
  }

  public class AddLoanLeadDoc extends LoanEndPointRequest<com.buy.housing.backend.loanEndPoint.model.LoanResponse> {

    private static final String REST_PATH = "addLoanLeadDoc/{id}/{token}/{loanId}";

    /**
     * Create a request for the method "addLoanLeadDoc".
     *
     * This request holds the parameters needed by the the loanEndPoint server.  After setting any
     * optional parameters, call the {@link AddLoanLeadDoc#execute()} method to invoke the remote
     * operation. <p> {@link AddLoanLeadDoc#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @param token
     * @param loanId
     * @param content the {@link com.buy.housing.backend.loanEndPoint.model.Document}
     * @since 1.13
     */
    protected AddLoanLeadDoc(java.lang.Long id, java.lang.String token, java.lang.Long loanId, com.buy.housing.backend.loanEndPoint.model.Document content) {
      super(LoanEndPoint.this, "POST", REST_PATH, content, com.buy.housing.backend.loanEndPoint.model.LoanResponse.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
      this.loanId = com.google.api.client.util.Preconditions.checkNotNull(loanId, "Required parameter loanId must be specified.");
    }

    @Override
    public AddLoanLeadDoc setAlt(java.lang.String alt) {
      return (AddLoanLeadDoc) super.setAlt(alt);
    }

    @Override
    public AddLoanLeadDoc setFields(java.lang.String fields) {
      return (AddLoanLeadDoc) super.setFields(fields);
    }

    @Override
    public AddLoanLeadDoc setKey(java.lang.String key) {
      return (AddLoanLeadDoc) super.setKey(key);
    }

    @Override
    public AddLoanLeadDoc setOauthToken(java.lang.String oauthToken) {
      return (AddLoanLeadDoc) super.setOauthToken(oauthToken);
    }

    @Override
    public AddLoanLeadDoc setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddLoanLeadDoc) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddLoanLeadDoc setQuotaUser(java.lang.String quotaUser) {
      return (AddLoanLeadDoc) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddLoanLeadDoc setUserIp(java.lang.String userIp) {
      return (AddLoanLeadDoc) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public AddLoanLeadDoc setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String token;

    /**

     */
    public java.lang.String getToken() {
      return token;
    }

    public AddLoanLeadDoc setToken(java.lang.String token) {
      this.token = token;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long loanId;

    /**

     */
    public java.lang.Long getLoanId() {
      return loanId;
    }

    public AddLoanLeadDoc setLoanId(java.lang.Long loanId) {
      this.loanId = loanId;
      return this;
    }

    @Override
    public AddLoanLeadDoc set(String parameterName, Object value) {
      return (AddLoanLeadDoc) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "addTimeLine".
   *
   * This request holds the parameters needed by the loanEndPoint server.  After setting any optional
   * parameters, call the {@link AddTimeLine#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param token
   * @param loanId
   * @param content the {@link com.buy.housing.backend.loanEndPoint.model.TimeLineStats}
   * @return the request
   */
  public AddTimeLine addTimeLine(java.lang.Long id, java.lang.String token, java.lang.Long loanId, com.buy.housing.backend.loanEndPoint.model.TimeLineStats content) throws java.io.IOException {
    AddTimeLine result = new AddTimeLine(id, token, loanId, content);
    initialize(result);
    return result;
  }

  public class AddTimeLine extends LoanEndPointRequest<com.buy.housing.backend.loanEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "addTimeLine/{id}/{token}/{loanId}";

    /**
     * Create a request for the method "addTimeLine".
     *
     * This request holds the parameters needed by the the loanEndPoint server.  After setting any
     * optional parameters, call the {@link AddTimeLine#execute()} method to invoke the remote
     * operation. <p> {@link
     * AddTimeLine#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param token
     * @param loanId
     * @param content the {@link com.buy.housing.backend.loanEndPoint.model.TimeLineStats}
     * @since 1.13
     */
    protected AddTimeLine(java.lang.Long id, java.lang.String token, java.lang.Long loanId, com.buy.housing.backend.loanEndPoint.model.TimeLineStats content) {
      super(LoanEndPoint.this, "POST", REST_PATH, content, com.buy.housing.backend.loanEndPoint.model.CommonResponse.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
      this.loanId = com.google.api.client.util.Preconditions.checkNotNull(loanId, "Required parameter loanId must be specified.");
    }

    @Override
    public AddTimeLine setAlt(java.lang.String alt) {
      return (AddTimeLine) super.setAlt(alt);
    }

    @Override
    public AddTimeLine setFields(java.lang.String fields) {
      return (AddTimeLine) super.setFields(fields);
    }

    @Override
    public AddTimeLine setKey(java.lang.String key) {
      return (AddTimeLine) super.setKey(key);
    }

    @Override
    public AddTimeLine setOauthToken(java.lang.String oauthToken) {
      return (AddTimeLine) super.setOauthToken(oauthToken);
    }

    @Override
    public AddTimeLine setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddTimeLine) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddTimeLine setQuotaUser(java.lang.String quotaUser) {
      return (AddTimeLine) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddTimeLine setUserIp(java.lang.String userIp) {
      return (AddTimeLine) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public AddTimeLine setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String token;

    /**

     */
    public java.lang.String getToken() {
      return token;
    }

    public AddTimeLine setToken(java.lang.String token) {
      this.token = token;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long loanId;

    /**

     */
    public java.lang.Long getLoanId() {
      return loanId;
    }

    public AddTimeLine setLoanId(java.lang.Long loanId) {
      this.loanId = loanId;
      return this;
    }

    @Override
    public AddTimeLine set(String parameterName, Object value) {
      return (AddTimeLine) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "applyForLoan".
   *
   * This request holds the parameters needed by the loanEndPoint server.  After setting any optional
   * parameters, call the {@link ApplyForLoan#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.buy.housing.backend.loanEndPoint.model.LoanLead}
   * @return the request
   */
  public ApplyForLoan applyForLoan(com.buy.housing.backend.loanEndPoint.model.LoanLead content) throws java.io.IOException {
    ApplyForLoan result = new ApplyForLoan(content);
    initialize(result);
    return result;
  }

  public class ApplyForLoan extends LoanEndPointRequest<com.buy.housing.backend.loanEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "applyForLoan";

    /**
     * Create a request for the method "applyForLoan".
     *
     * This request holds the parameters needed by the the loanEndPoint server.  After setting any
     * optional parameters, call the {@link ApplyForLoan#execute()} method to invoke the remote
     * operation. <p> {@link
     * ApplyForLoan#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.buy.housing.backend.loanEndPoint.model.LoanLead}
     * @since 1.13
     */
    protected ApplyForLoan(com.buy.housing.backend.loanEndPoint.model.LoanLead content) {
      super(LoanEndPoint.this, "POST", REST_PATH, content, com.buy.housing.backend.loanEndPoint.model.CommonResponse.class);
    }

    @Override
    public ApplyForLoan setAlt(java.lang.String alt) {
      return (ApplyForLoan) super.setAlt(alt);
    }

    @Override
    public ApplyForLoan setFields(java.lang.String fields) {
      return (ApplyForLoan) super.setFields(fields);
    }

    @Override
    public ApplyForLoan setKey(java.lang.String key) {
      return (ApplyForLoan) super.setKey(key);
    }

    @Override
    public ApplyForLoan setOauthToken(java.lang.String oauthToken) {
      return (ApplyForLoan) super.setOauthToken(oauthToken);
    }

    @Override
    public ApplyForLoan setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ApplyForLoan) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ApplyForLoan setQuotaUser(java.lang.String quotaUser) {
      return (ApplyForLoan) super.setQuotaUser(quotaUser);
    }

    @Override
    public ApplyForLoan setUserIp(java.lang.String userIp) {
      return (ApplyForLoan) super.setUserIp(userIp);
    }

    @Override
    public ApplyForLoan set(String parameterName, Object value) {
      return (ApplyForLoan) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "approveLoanEnquiry".
   *
   * This request holds the parameters needed by the loanEndPoint server.  After setting any optional
   * parameters, call the {@link ApproveLoanEnquiry#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param token
   * @param loanId
   * @param approve
   * @param content the {@link com.buy.housing.backend.loanEndPoint.model.LoanLead}
   * @return the request
   */
  public ApproveLoanEnquiry approveLoanEnquiry(java.lang.Long id, java.lang.String token, java.lang.Long loanId, java.lang.Boolean approve, com.buy.housing.backend.loanEndPoint.model.LoanLead content) throws java.io.IOException {
    ApproveLoanEnquiry result = new ApproveLoanEnquiry(id, token, loanId, approve, content);
    initialize(result);
    return result;
  }

  public class ApproveLoanEnquiry extends LoanEndPointRequest<com.buy.housing.backend.loanEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "approveLoanEnquiry/{id}/{token}/{loanId}/{approve}";

    /**
     * Create a request for the method "approveLoanEnquiry".
     *
     * This request holds the parameters needed by the the loanEndPoint server.  After setting any
     * optional parameters, call the {@link ApproveLoanEnquiry#execute()} method to invoke the remote
     * operation. <p> {@link ApproveLoanEnquiry#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @param token
     * @param loanId
     * @param approve
     * @param content the {@link com.buy.housing.backend.loanEndPoint.model.LoanLead}
     * @since 1.13
     */
    protected ApproveLoanEnquiry(java.lang.Long id, java.lang.String token, java.lang.Long loanId, java.lang.Boolean approve, com.buy.housing.backend.loanEndPoint.model.LoanLead content) {
      super(LoanEndPoint.this, "POST", REST_PATH, content, com.buy.housing.backend.loanEndPoint.model.CommonResponse.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
      this.loanId = com.google.api.client.util.Preconditions.checkNotNull(loanId, "Required parameter loanId must be specified.");
      this.approve = com.google.api.client.util.Preconditions.checkNotNull(approve, "Required parameter approve must be specified.");
    }

    @Override
    public ApproveLoanEnquiry setAlt(java.lang.String alt) {
      return (ApproveLoanEnquiry) super.setAlt(alt);
    }

    @Override
    public ApproveLoanEnquiry setFields(java.lang.String fields) {
      return (ApproveLoanEnquiry) super.setFields(fields);
    }

    @Override
    public ApproveLoanEnquiry setKey(java.lang.String key) {
      return (ApproveLoanEnquiry) super.setKey(key);
    }

    @Override
    public ApproveLoanEnquiry setOauthToken(java.lang.String oauthToken) {
      return (ApproveLoanEnquiry) super.setOauthToken(oauthToken);
    }

    @Override
    public ApproveLoanEnquiry setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ApproveLoanEnquiry) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ApproveLoanEnquiry setQuotaUser(java.lang.String quotaUser) {
      return (ApproveLoanEnquiry) super.setQuotaUser(quotaUser);
    }

    @Override
    public ApproveLoanEnquiry setUserIp(java.lang.String userIp) {
      return (ApproveLoanEnquiry) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public ApproveLoanEnquiry setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String token;

    /**

     */
    public java.lang.String getToken() {
      return token;
    }

    public ApproveLoanEnquiry setToken(java.lang.String token) {
      this.token = token;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long loanId;

    /**

     */
    public java.lang.Long getLoanId() {
      return loanId;
    }

    public ApproveLoanEnquiry setLoanId(java.lang.Long loanId) {
      this.loanId = loanId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean approve;

    /**

     */
    public java.lang.Boolean getApprove() {
      return approve;
    }

    public ApproveLoanEnquiry setApprove(java.lang.Boolean approve) {
      this.approve = approve;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean loanByThirdParty;

    /**

     */
    public java.lang.Boolean getLoanByThirdParty() {
      return loanByThirdParty;
    }

    public ApproveLoanEnquiry setLoanByThirdParty(java.lang.Boolean loanByThirdParty) {
      this.loanByThirdParty = loanByThirdParty;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String remarks;

    /**

     */
    public java.lang.String getRemarks() {
      return remarks;
    }

    public ApproveLoanEnquiry setRemarks(java.lang.String remarks) {
      this.remarks = remarks;
      return this;
    }

    @Override
    public ApproveLoanEnquiry set(String parameterName, Object value) {
      return (ApproveLoanEnquiry) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "changeLoanStatus".
   *
   * This request holds the parameters needed by the loanEndPoint server.  After setting any optional
   * parameters, call the {@link ChangeLoanStatus#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param token
   * @param loanId
   * @param oldState
   * @param newState
   * @param content the {@link com.buy.housing.backend.loanEndPoint.model.LoanLead}
   * @return the request
   */
  public ChangeLoanStatus changeLoanStatus(java.lang.Long id, java.lang.String token, java.lang.Long loanId, java.lang.String oldState, java.lang.String newState, com.buy.housing.backend.loanEndPoint.model.LoanLead content) throws java.io.IOException {
    ChangeLoanStatus result = new ChangeLoanStatus(id, token, loanId, oldState, newState, content);
    initialize(result);
    return result;
  }

  public class ChangeLoanStatus extends LoanEndPointRequest<com.buy.housing.backend.loanEndPoint.model.CommonResponse> {

    private static final String REST_PATH = "changeLoanStatus/{id}/{token}/{loanId}/{oldState}/{newState}";

    /**
     * Create a request for the method "changeLoanStatus".
     *
     * This request holds the parameters needed by the the loanEndPoint server.  After setting any
     * optional parameters, call the {@link ChangeLoanStatus#execute()} method to invoke the remote
     * operation. <p> {@link ChangeLoanStatus#initialize(com.google.api.client.googleapis.services.Abs
     * tractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @param token
     * @param loanId
     * @param oldState
     * @param newState
     * @param content the {@link com.buy.housing.backend.loanEndPoint.model.LoanLead}
     * @since 1.13
     */
    protected ChangeLoanStatus(java.lang.Long id, java.lang.String token, java.lang.Long loanId, java.lang.String oldState, java.lang.String newState, com.buy.housing.backend.loanEndPoint.model.LoanLead content) {
      super(LoanEndPoint.this, "POST", REST_PATH, content, com.buy.housing.backend.loanEndPoint.model.CommonResponse.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
      this.loanId = com.google.api.client.util.Preconditions.checkNotNull(loanId, "Required parameter loanId must be specified.");
      this.oldState = com.google.api.client.util.Preconditions.checkNotNull(oldState, "Required parameter oldState must be specified.");
      this.newState = com.google.api.client.util.Preconditions.checkNotNull(newState, "Required parameter newState must be specified.");
    }

    @Override
    public ChangeLoanStatus setAlt(java.lang.String alt) {
      return (ChangeLoanStatus) super.setAlt(alt);
    }

    @Override
    public ChangeLoanStatus setFields(java.lang.String fields) {
      return (ChangeLoanStatus) super.setFields(fields);
    }

    @Override
    public ChangeLoanStatus setKey(java.lang.String key) {
      return (ChangeLoanStatus) super.setKey(key);
    }

    @Override
    public ChangeLoanStatus setOauthToken(java.lang.String oauthToken) {
      return (ChangeLoanStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public ChangeLoanStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ChangeLoanStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ChangeLoanStatus setQuotaUser(java.lang.String quotaUser) {
      return (ChangeLoanStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public ChangeLoanStatus setUserIp(java.lang.String userIp) {
      return (ChangeLoanStatus) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public ChangeLoanStatus setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String token;

    /**

     */
    public java.lang.String getToken() {
      return token;
    }

    public ChangeLoanStatus setToken(java.lang.String token) {
      this.token = token;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long loanId;

    /**

     */
    public java.lang.Long getLoanId() {
      return loanId;
    }

    public ChangeLoanStatus setLoanId(java.lang.Long loanId) {
      this.loanId = loanId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String oldState;

    /**

     */
    public java.lang.String getOldState() {
      return oldState;
    }

    public ChangeLoanStatus setOldState(java.lang.String oldState) {
      this.oldState = oldState;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String newState;

    /**

     */
    public java.lang.String getNewState() {
      return newState;
    }

    public ChangeLoanStatus setNewState(java.lang.String newState) {
      this.newState = newState;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String remarks;

    /**

     */
    public java.lang.String getRemarks() {
      return remarks;
    }

    public ChangeLoanStatus setRemarks(java.lang.String remarks) {
      this.remarks = remarks;
      return this;
    }

    @Override
    public ChangeLoanStatus set(String parameterName, Object value) {
      return (ChangeLoanStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getLoanLeadById".
   *
   * This request holds the parameters needed by the loanEndPoint server.  After setting any optional
   * parameters, call the {@link GetLoanLeadById#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param token
   * @param loanId
   * @return the request
   */
  public GetLoanLeadById getLoanLeadById(java.lang.Long id, java.lang.String token, java.lang.Long loanId) throws java.io.IOException {
    GetLoanLeadById result = new GetLoanLeadById(id, token, loanId);
    initialize(result);
    return result;
  }

  public class GetLoanLeadById extends LoanEndPointRequest<com.buy.housing.backend.loanEndPoint.model.LoanResponse> {

    private static final String REST_PATH = "loanresponse/{id}/{token}/{loanId}";

    /**
     * Create a request for the method "getLoanLeadById".
     *
     * This request holds the parameters needed by the the loanEndPoint server.  After setting any
     * optional parameters, call the {@link GetLoanLeadById#execute()} method to invoke the remote
     * operation. <p> {@link GetLoanLeadById#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @param token
     * @param loanId
     * @since 1.13
     */
    protected GetLoanLeadById(java.lang.Long id, java.lang.String token, java.lang.Long loanId) {
      super(LoanEndPoint.this, "GET", REST_PATH, null, com.buy.housing.backend.loanEndPoint.model.LoanResponse.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
      this.loanId = com.google.api.client.util.Preconditions.checkNotNull(loanId, "Required parameter loanId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetLoanLeadById setAlt(java.lang.String alt) {
      return (GetLoanLeadById) super.setAlt(alt);
    }

    @Override
    public GetLoanLeadById setFields(java.lang.String fields) {
      return (GetLoanLeadById) super.setFields(fields);
    }

    @Override
    public GetLoanLeadById setKey(java.lang.String key) {
      return (GetLoanLeadById) super.setKey(key);
    }

    @Override
    public GetLoanLeadById setOauthToken(java.lang.String oauthToken) {
      return (GetLoanLeadById) super.setOauthToken(oauthToken);
    }

    @Override
    public GetLoanLeadById setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetLoanLeadById) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetLoanLeadById setQuotaUser(java.lang.String quotaUser) {
      return (GetLoanLeadById) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetLoanLeadById setUserIp(java.lang.String userIp) {
      return (GetLoanLeadById) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetLoanLeadById setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String token;

    /**

     */
    public java.lang.String getToken() {
      return token;
    }

    public GetLoanLeadById setToken(java.lang.String token) {
      this.token = token;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long loanId;

    /**

     */
    public java.lang.Long getLoanId() {
      return loanId;
    }

    public GetLoanLeadById setLoanId(java.lang.Long loanId) {
      this.loanId = loanId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long bookingId;

    /**

     */
    public java.lang.Long getBookingId() {
      return bookingId;
    }

    public GetLoanLeadById setBookingId(java.lang.Long bookingId) {
      this.bookingId = bookingId;
      return this;
    }

    @Override
    public GetLoanLeadById set(String parameterName, Object value) {
      return (GetLoanLeadById) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getLoanLeads".
   *
   * This request holds the parameters needed by the loanEndPoint server.  After setting any optional
   * parameters, call the {@link GetLoanLeads#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param token
   * @param offset
   * @param limit
   * @return the request
   */
  public GetLoanLeads getLoanLeads(java.lang.Long id, java.lang.String token, java.lang.Integer offset, java.lang.Integer limit) throws java.io.IOException {
    GetLoanLeads result = new GetLoanLeads(id, token, offset, limit);
    initialize(result);
    return result;
  }

  public class GetLoanLeads extends LoanEndPointRequest<com.buy.housing.backend.loanEndPoint.model.LoanListResponse> {

    private static final String REST_PATH = "loanlistresponse/{id}/{token}/{offset}/{limit}";

    /**
     * Create a request for the method "getLoanLeads".
     *
     * This request holds the parameters needed by the the loanEndPoint server.  After setting any
     * optional parameters, call the {@link GetLoanLeads#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetLoanLeads#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @param token
     * @param offset
     * @param limit
     * @since 1.13
     */
    protected GetLoanLeads(java.lang.Long id, java.lang.String token, java.lang.Integer offset, java.lang.Integer limit) {
      super(LoanEndPoint.this, "GET", REST_PATH, null, com.buy.housing.backend.loanEndPoint.model.LoanListResponse.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
      this.offset = com.google.api.client.util.Preconditions.checkNotNull(offset, "Required parameter offset must be specified.");
      this.limit = com.google.api.client.util.Preconditions.checkNotNull(limit, "Required parameter limit must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetLoanLeads setAlt(java.lang.String alt) {
      return (GetLoanLeads) super.setAlt(alt);
    }

    @Override
    public GetLoanLeads setFields(java.lang.String fields) {
      return (GetLoanLeads) super.setFields(fields);
    }

    @Override
    public GetLoanLeads setKey(java.lang.String key) {
      return (GetLoanLeads) super.setKey(key);
    }

    @Override
    public GetLoanLeads setOauthToken(java.lang.String oauthToken) {
      return (GetLoanLeads) super.setOauthToken(oauthToken);
    }

    @Override
    public GetLoanLeads setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetLoanLeads) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetLoanLeads setQuotaUser(java.lang.String quotaUser) {
      return (GetLoanLeads) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetLoanLeads setUserIp(java.lang.String userIp) {
      return (GetLoanLeads) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetLoanLeads setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String token;

    /**

     */
    public java.lang.String getToken() {
      return token;
    }

    public GetLoanLeads setToken(java.lang.String token) {
      this.token = token;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer offset;

    /**

     */
    public java.lang.Integer getOffset() {
      return offset;
    }

    public GetLoanLeads setOffset(java.lang.Integer offset) {
      this.offset = offset;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public GetLoanLeads setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String phone;

    /**

     */
    public java.lang.String getPhone() {
      return phone;
    }

    public GetLoanLeads setPhone(java.lang.String phone) {
      this.phone = phone;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String type;

    /**

     */
    public java.lang.String getType() {
      return type;
    }

    public GetLoanLeads setType(java.lang.String type) {
      this.type = type;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long project;

    /**

     */
    public java.lang.Long getProject() {
      return project;
    }

    public GetLoanLeads setProject(java.lang.Long project) {
      this.project = project;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long city;

    /**

     */
    public java.lang.Long getCity() {
      return city;
    }

    public GetLoanLeads setCity(java.lang.Long city) {
      this.city = city;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String state;

    /**

     */
    public java.lang.String getState() {
      return state;
    }

    public GetLoanLeads setState(java.lang.String state) {
      this.state = state;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean external;

    /**

     */
    public java.lang.Boolean getExternal() {
      return external;
    }

    public GetLoanLeads setExternal(java.lang.Boolean external) {
      this.external = external;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean outside;

    /**

     */
    public java.lang.Boolean getOutside() {
      return outside;
    }

    public GetLoanLeads setOutside(java.lang.Boolean outside) {
      this.outside = outside;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean stats;

    /**

     */
    public java.lang.Boolean getStats() {
      return stats;
    }

    public GetLoanLeads setStats(java.lang.Boolean stats) {
      this.stats = stats;
      return this;
    }

    @Override
    public GetLoanLeads set(String parameterName, Object value) {
      return (GetLoanLeads) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link LoanEndPoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link LoanEndPoint}. */
    @Override
    public LoanEndPoint build() {
      return new LoanEndPoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }



    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link LoanEndPointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setLoanEndPointRequestInitializer(
        LoanEndPointRequestInitializer loanendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(loanendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
