/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-09-26 19:19:48 UTC)
 * on 2017-10-10 at 06:54:35 UTC 
 * Modify at your own risk.
 */

package com.buy.housing.backend.newsEndPoint.model;

/**
 * Model definition for AgentCheckInHistory.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the newsEndPoint. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AgentCheckInHistory extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long agentId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long agentName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private Long time;

  /**
   * @return value or {@code null} for none
   */
  public Long getAgentId() {
    return agentId;
  }

  /**
   * @param agentId agentId or {@code null} for none
   */
  public AgentCheckInHistory setAgentId(Long agentId) {
    this.agentId = agentId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Long getAgentName() {
    return agentName;
  }

  /**
   * @param agentName agentName or {@code null} for none
   */
  public AgentCheckInHistory setAgentName(Long agentName) {
    this.agentName = agentName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public AgentCheckInHistory setDescription(String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public AgentCheckInHistory setId(Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Long getTime() {
    return time;
  }

  /**
   * @param time time or {@code null} for none
   */
  public AgentCheckInHistory setTime(Long time) {
    this.time = time;
    return this;
  }

  @Override
  public AgentCheckInHistory set(String fieldName, Object value) {
    return (AgentCheckInHistory) super.set(fieldName, value);
  }

  @Override
  public AgentCheckInHistory clone() {
    return (AgentCheckInHistory) super.clone();
  }

}
